### ISSUE TITLE
Table maintenance: Error from RS_GET_ALL_INCLUDES 

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1100] opened 2018-01-08 14:35 UTC
I get the following error with a table maintenance dialog.
![image](https://user-images.githubusercontent.com/17437789/34675265-52e05330-f489-11e7-95bd-90528a95ca2b.png)

Steps to reproduce.
1) Create a repository with a db table and a table maintenance dialog.
2) Commit the changes 
3) Delete the table maintenance dialog with this options
![image](https://user-images.githubusercontent.com/17437789/34675288-732eb1cc-f489-11e7-8bdb-36d2767bd4e1.png)

4) Recreate the table maintenance dialog into the same function group as before
5) Refresh in abapGit

![image](https://user-images.githubusercontent.com/17437789/34675398-cc3f7cd8-f489-11e7-84b9-7b0aac550228.png)

**Comment by EduardoCopat** [comment] 2018-05-11 20:56
Some analysis I've been doing, it may help us to solve this issue. Here are the `progdir` of a few scenarios, obtained in [this line](https://github.com/larshp/abapGit/blob/83a38a124bea1d42015c67216f59bc1c59dfa050/src/objects/zcl_abapgit_object_fugr.clas.abap#L791)

1. A regular function group

![image](https://user-images.githubusercontent.com/2248490/39945478-f8790266-5540-11e8-8930-70e562243bf5.png)

2. A generated function group 

![image](https://user-images.githubusercontent.com/2248490/39945702-cd521bb2-5541-11e8-91b0-0834b9f50b34.png)

3. A generated function group, just deleted, as in step 3 of this issue

![image](https://user-images.githubusercontent.com/2248490/39945720-dce3c6a2-5541-11e8-8129-dedebae28df7.png)

4. The deleted function group, regenerated again as in step 4

![image](https://user-images.githubusercontent.com/2248490/39946041-0fc16fce-5543-11e8-917b-957ede6bd7bb.png)


So, apparently:

Type | SQLX | SUBC
------------ | -------------|-------------
A regular function group |  | F
A generated function group | X | F
A deleted generated function group | X | I
A regenerated group|X|I

What if we do a validation if table `TVDIR` does not contain a line with `area = function group`, and check if the `SQLX` is `X` and `SUBC` = `I`. 

If the above is true, we can eliminate it from serialization.

**Comment by christianguenter2** [comment] 2018-05-13 08:28
For me this looks like a bug in SAP standard. Maybe we should just ingnore it? Workaround would be the delete and recreate the function group.

**Comment by mbtools** [comment] 2020-07-16 02:30
Hi Christian,
I tried to reproduce this error but it seems to be working fine with the current AG version. Close it?

PS: There are many diffs due to changes in AG. If there are still issues with tab maint fugr, let's create a fresh test repo.

**Closed** 2020-07-16 05:32 UTC
Labels: bug
