### ISSUE TITLE
Importing zip into offline-repo: Multiple transport pop-ups

### ISSUE THREAD

**Issue by mrsimpson** [larshp/abapGit#497] opened 2016-12-13 13:04 UTC
when importing into a zip-file a new system, the package selection popup is being displayed for each object.

**Comment by larshp** [comment] 2016-12-13 13:05
yea, I think it depends on the object type how the transport is handled, but this is definitely something we should look into

**Comment by mrsimpson** [comment] 2016-12-13 13:08
Might also depend on included packages. Just imported the abapgit-plugins and didn't experience the behaviour

**Comment by christian1020-94** [comment] 2017-01-22 23:13
How can I reproduce this bug?

**Comment by mrsimpson** [comment] 2017-01-23 19:30
Try this zip: https://github.com/mrsimpson/p2p-help-abap-client/archive/master.zip

**Comment by christian1020-94** [comment] 2017-01-23 20:19
I'm getting an Object type AVAS not supported, because of the .avas files. I guess I should just delete them?

**Comment by mrsimpson** [comment] 2017-01-23 20:55
Deleting them might make a difference, but I don't know. Give it a try and see whether it occurs. If not, install the abapGit plugins

**Comment by larshp** [comment] 2017-01-24 06:20
The package selection popups are object type dependent, so the same issue should occur with online repositories.

Perhaps calling TR_TADIR_INTERFACE before the object type API call will help

**Comment by larshp** [comment] 2017-02-18 12:31
@mrsimpson try this https://github.com/larshp/abapGit/pull/632

**Comment by larshp** [comment] 2017-11-18 09:07
try again, implemented in https://github.com/larshp/abapGit/issues/1042

closing, please open new issue in case of bugs/questions

**Closed by larshp** 2017-11-18 09:07 UTC
Labels: bug, low priority
