### ISSUE TITLE
ZCL_ABAPGIT_PERSIST_INJECTOR and ZCL_ABAPGIT_INJECTOR is not in zabapgit.abap 

### ISSUE THREAD

**Issue by hismayilov** [larshp/abapGit#3418] opened 2020-05-24 23:02 UTC
Folllwoing classes is not included in [zabapgit.abap ](https://raw.githubusercontent.com/abapGit/build/master/zabapgit.abap)

1. [ZCL_ABAPGIT_PERSIST_INJECTOR](https://github.com/larshp/abapGit/blob/6f6338bc67eb9d8c4549cee242918badef9354cd/src/persist/zcl_abapgit_persist_injector.clas.abap)

2. [ZCL_ABAPGIT_INJECTOR](https://github.com/larshp/abapGit/blob/543114963f0df694be185cf5f97e171926d2f0f2/src/zcl_abapgit_injector.clas.abap)

**Comment by larshp** [comment] 2020-05-25 03:37
all classes "FOR TESTING" are skipped by abapmerge, https://github.com/larshp/abapmerge

do you need them in the report?

**Comment by mfallen** [comment] 2020-05-25 04:58
> all classes "FOR TESTING" are skipped by abapmerge, https://github.com/larshp/abapmerge
> 
> do you need them in the report?

They are needed as called in the actual version. So you can't activate, error "Type "ZCL_ABAPGIT_PERSIST_INJECTOR" is unknown", line 9574

`CLASS zcl_abapgit_persist_factory DEFINITION
  CREATE PRIVATE
  FRIENDS ZCL_ABAPGIT_persist_injector .`

**Comment by larshp** [comment] 2020-05-25 05:21
thanks, try again, latest version

**Comment by mfallen** [comment] 2020-05-25 05:25
> thanks, try again, latest version

Working again, thanks!

**Comment by larshp** [comment] 2020-05-25 05:28
cool 👍 

Todo: 
* abapmerge 0.14.0 must be changed to handle the global FOR TESTING classes different
* abaplint should report error for the compiled report, opened https://github.com/abaplint/abaplint/issues/899

**Comment by larshp** [comment] 2020-05-26 16:14
closing, root cause will be solved by https://github.com/larshp/abapmerge/issues/102 and https://github.com/abaplint/abaplint/issues/899

**Closed** 2020-05-26 16:14 UTC
