### ISSUE TITLE
Errors when activating: include missing

### ISSUE THREAD

**Issue by nununo** [larshp/abapGit#305] opened 2016-08-31 10:45 UTC
Hello,

I'm getting errors when activating the objects:

![image](https://cloud.githubusercontent.com/assets/532049/18125780/3f1a0c48-6f78-11e6-90a1-cc8a60901123.png)

At first I thought it was a question of activation order because before I had it and solved it by manually activating the objects in the right order. But now it seems it is missing one include:

![image](https://cloud.githubusercontent.com/assets/532049/18125834/98717fba-6f78-11e6-913f-f7de91b95839.png)

I am importing from a ZIP into which I exported the whole package including this missing include.

Please advise.

Regards,
Nuno

**Comment by larshp** [comment] 2016-08-31 10:53
I guess this is a function group? The function groups have a few problems, and the issue for it is not yet closed, https://github.com/larshp/abapGit/issues/15

Is the missing include part of the zip file?

Can you try creating a dummy function group to see if the issue can be reproduced? And provide steps to reproduce.

**Comment by larshp** [comment] 2016-08-31 11:07
abapGit uses function module RS_GET_ALL_INCLUDES to find all relevant includes for the function group, can you try executing it in your system to see if it finds the missing include?

https://github.com/larshp/abapGit/blob/master/src/zabapgit_object.prog.abap#L1782

**Comment by larshp** [comment] 2016-08-31 13:03
is the function group generated via the table maintenance generator?

**Comment by nununo** [comment] 2016-08-31 13:08
Yes it was. The function group was not created manually. It was generated automatically through SE11 when generating the maintenance views for the 1st of the 3 tables it currently supports. No other custom function modules there. Just generated code.

Do you think manually creating the function group and only then using it to generate the maintenance views would make a difference? I could try if you think it's worth it.

**Comment by larshp** [comment] 2016-08-31 13:22
It is more the fact that the code was created by the maintenance generator.

I've reproduced the issue, take any database table and generate a table maintenance. Export/push the code. Include LZASDFT00(in this case) is not exported,

![image](https://cloud.githubusercontent.com/assets/5888506/18130248/8ae9dad4-6f8e-11e6-9395-20d32f99763e.png)

**Comment by larshp** [comment] 2016-08-31 14:03
Hmm, it looks like the T00 include is a "reserved name", also it is not possible to edit the include. Could fetch all includes from database table RSEUINC, and serialize it, however I feel like it will make issues creating a locked include.

Another approach(earlier discussed with @sbcgua ): dont serialize all the abap code for function groups only containing generated table maintenance views, instead just serialize the meta data, and at installation call the SAP standard code to generate the function group.

hmm

![image](https://cloud.githubusercontent.com/assets/5888506/18131675/fd16a902-6f93-11e6-9340-d93efefb4e9a.png)

**Comment by nununo** [comment] 2016-08-31 15:22
> Another approach(earlier discussed with @sbcgua ): dont serialize all the abap code for function groups only containing generated table maintenance views, instead just serialize the meta data, and at installation call the SAP standard code to generate the function group.

That seems to be an excellent idea! I just wonder how complex it may be... But since table maintenance generation function groups are so common, it would be great to find a solution for this particular issue.

My friend Nuno Morais (@WebworkApp) has worked on a dependencies check tool and has some experience with these SAP functions. Maybe he has an idea? Let's see what he says.

Thanks!
Nuno

**Comment by nununo** [comment] 2016-11-02 15:29
Hello Lars,

Did you find any solution for this one? It's a quite annoying one.

To bypass this problem I currently I've been keeping all the table maintenance function groups in a temporary isolated package and have to manually generate the table maintenance views on each target system.

Thanks,
Nuno

**Comment by larshp** [comment] 2016-11-02 15:34
no, have not had time to look into it :(

**Comment by nununo** [comment] 2016-11-02 15:48
Sure. You already do so much! Anyway I was not pushing, just curious to know :)

Thanks!

**Comment by nununo** [comment] 2016-11-02 15:49
I am not familiar with this generation of standard code on which you're proficient :) but if I find a way to do it I'll try to fix it myself.

**Comment by larshp** [comment] 2016-11-02 15:54
I'm not proficient :smile: will also have to look into how the standard generation works

**Comment by EduardoCopat** [comment] 2017-01-19 10:27
I could not find any APIs to generate views. The package where generation is done is `SVIM`.

Following the ideas above: Serialize the metadata from transaction `SE55` and use [CALL TRANSACTION with Batch input](https://wiki.scn.sap.com/wiki/display/ABAP/Batch+Input+-+BDC) to manually generate/delete the "generated function groups".

Still open: How to know if a Function Group is generated or not?

**Comment by larshp** [comment] 2017-01-19 11:05
API: is it possible to do a series of `PERFORM IN PROGRAM`?

Regenerate function group: one approach could be always regenerate the function group in case the corresponding table has been changed today. This is easy, it will be difficult to make a perfect solution without a lot of refactoring.

**Comment by EduardoCopat** [comment] 2017-01-19 14:15
It may be possible, but the forms there weren't very...friendly.

**Comment by larshp** [comment] 2017-02-22 16:19
now merged into master, make sure to add the T00 include, and the function group should activate without errrors

try again

**Comment by larshp** [comment] 2017-03-21 11:43
closing, open new issue if the include is still causing issues

**Closed by larshp** 2017-03-21 11:43 UTC
Labels: bug
