### ISSUE TITLE
Syntax highlighter: xml attributes

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1408] opened 2018-05-21 07:11 UTC
I get
`VERSION=" VERSION="1.5" DOWNLOADDATE=" DOWNLOADDATE="" DOWNLOADTIME=" DOWNLOADTIME=""`
anybody else have the same error?

![image](https://user-images.githubusercontent.com/5888506/40294660-d287bd0c-5cd6-11e8-81f8-9ebb38c565b3.png)

**Comment by christianguenter2** [comment] 2018-05-22 09:47
No issues on our side.

**Comment by larshp** [comment] 2018-05-27 15:26
try cloning https://github.com/larshp/DOMA

note that the remote,
`<ECTD SAPRL="751" VERSION="1.5" DOWNLOADDATE="" DOWNLOADTIME=" DOWNLOADTIME="">`
does not match what is actually in the repository
`<ECTD SAPRL="751" VERSION="1.5" DOWNLOADDATE="" DOWNLOADTIME="">`

perhaps an issue in the code highlighter?

**Comment by larshp** [comment] 2018-05-27 15:37
Update: it is an issue in the highlighter,

```
    DATA: lv_line   TYPE string,
          lo_syntax TYPE REF TO zcl_abapgit_syntax_highlighter.

    lv_line = '<ECTD SAPRL="751" VERSION="1.5" DOWNLOADDATE="" DOWNLOADTIME="">'.

    lo_syntax = zcl_abapgit_syntax_highlighter=>create( '*.xml' ).
    DATA(lv_result) = lo_syntax->process_line( lv_line ).
```

produces

![image](https://user-images.githubusercontent.com/5888506/40587795-853fc320-61d4-11e8-8c6d-b4e2066b9342.png)

note "DOWNLOADTIME" which appears twice in the result, but once in the input

**Comment by christianguenter2** [comment] 2018-06-02 20:32
the problem is caused by empty xml attributes.

Either we adjust the attribute value regex here. 
https://github.com/larshp/abapGit/blob/c02e6533c8130fcbbf6e055259c4b0cf0363b8b2/src/syntax/zcl_abapgit_syntax_xml.clas.abap#L24

Or we change the ecatt implemenation that the attributes are not cleared but removed.
https://github.com/larshp/abapGit/blob/87f1d913fbd3b2ee4401573fce83a128092fe747/src/objects/zcl_abapgit_object_ecatt_super.clas.abap#L146-L152

Or both.

**Comment by larshp** [comment] 2018-06-03 05:18
both, syntax highlighter to make sure we do not run into this problem again, ecatt to decrease the xml size

**Comment by christianguenter2** [comment] 2018-06-07 19:14
Closing...

**Closed by christianguenter2** 2018-06-07 19:14 UTC
Labels: bug
