### ISSUE TITLE
Table Index not supported

### ISSUE THREAD

**Issue by prashantagl** [larshp/abapGit#760] opened 2017-05-18 06:50 UTC
I have backed up table on Github repository, post deletion of table, i imported table back in dev. table is imported successfully but index was missing.

Tables Index is not supported?

**Comment by larshp** [comment] 2017-05-18 07:21
guess it is part of dd12v and dd17v,
https://github.com/larshp/abapGit/blob/master/src/zabapgit_object_tabl.prog.abap#L177

But not sure if it works, can you describe the steps to reproduce the issue?

**Comment by prashantagl** [comment] 2017-05-18 07:24
01. create any custom table, add any secondary index on any field.
02. back it up on github repository
03. delete the table
04. pull back the table from github repository
05. once imported successfully, check if the secondary index which you added is present or not.

**Comment by larshp** [comment] 2017-05-18 09:14
thanks

TOBJ: please create it as a separate issue

**Comment by larshp** [comment] 2017-05-18 15:48
Works for me, see https://github.com/larshp/CLAS/blob/master/src/ztable.tabl.xml

The index is added in the activation list, and exists after activation,

![image](https://cloud.githubusercontent.com/assets/5888506/26211141/11cc2298-3bf2-11e7-8d49-769633882977.png)

**Comment by larshp** [comment] 2017-06-03 08:56
@prashantagl can you try reproducing the problem in a public repository? just use some dummy objects

**Comment by christianguenter2** [comment] 2017-06-15 09:35
I'm also not able to reproduce the issue.

**Comment by larshp** [comment] 2017-06-15 09:38
I'll close it then, it is 28 days ago we heard anything from @prashantagl

**Closed by larshp** 2017-06-15 09:38 UTC
Labels: bug
