### ISSUE TITLE
Intermittent 411 errors connecting to Azure Repos

### ISSUE THREAD

**Issue by manb-msft** [larshp/abapGit#3296] opened 2020-04-07 10:52 UTC
Hello everyone, we have a team trying to use abapGit to connect to Azure Repos, and we keep seeing intermittent connectivity failures - to the point where it makes it really harder to use this - it works when it works, but breaks most of the time. We've ruled out most network issues by taking traces, but if there's any verbose logging that can be taken from abapGit, that'd be helpful too. 

I could not find related issues here, so I'm starting a new one. Has anyone else experienced this?

![image](https://user-images.githubusercontent.com/35102509/78660916-8ad3b780-78eb-11ea-9f19-f04df0414719.png)

**Comment by larshp** [comment] 2020-04-07 10:57
hmm, interesting

Sounds like the errors are periodical, and cannot reliably be reproduced?

Any proxies in the network setup from the SAP system to the git repo?

**Comment by manb-msft** [comment] 2020-04-07 11:05
@larshp Thanks for the really quick response! It is interesting, and it can be reproduced reliably. Some calls work, and then it breaks immediately - in a matter of 5 minutes. 
The team that I'm working with have temporarily opened up everything to see if that is fixed, but no help. I'm also having them use git command-line tools to see if the behavior is consistent there as well, possibly take a fiddler trace to rule out any software proxies. 

But when we tried running fiddler on the SAP Server when we ran this from a client, nothing was captured. Does abapGit use git tools internally or do they make Web Service calls to talk to git repos? (I'm really curious, and please forgive my limited understanding on how abapGit does it)

**Comment by larshp** [comment] 2020-04-07 12:38
abapGit implements the raw git protocol, and uses http for transport, the basic primitives are implemented in https://github.com/larshp/abapGit/tree/master/src/git

by enabling the ABAP debugger you can check all http requests and replies

can you try making a public Azure DevOps repository and check it is reproducible there?

**Comment by manb-msft** [comment] 2020-04-08 05:14
Thanks so much Lars. Those are some great suggestions. We will try those out and I'll update here once we find the cause/resolution.

**Comment by larshp** [comment] 2020-04-09 09:48
did few tests in https://dev.azure.com/larshvam/_git/public?_a=history, no errors occurred

**Comment by himanshush13** [comment] 2020-04-20 14:13
<img width="301" alt="Untitled" src="https://user-images.githubusercontent.com/36809136/79761240-cbe1b800-833e-11ea-9a4e-d62f332a54e7.png">

My case is something similar, but I can enter into the page where I can give comments and click on commit button, but then it is giving the unauthorized  error.
As directed, I have made my repo public, added certificates, but still no luck.

**Comment by larshp** [comment] 2020-04-20 14:46
@himanshush13 are you using tokens? https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page

**Comment by himanshush13** [comment] 2020-04-20 14:49
Thanks for your reply Lars, I used the tokens and it helped me committing the code to the azure repo. But one doubt, every time, I have to use the token, because the token will last for only 30 days, so, do I need to do it frequently on every commit ?

**Comment by larshp** [comment] 2020-04-20 14:52
thats up to you, abapGit does not store secret information for the user. You can keep the token somewhere, use a password manager or regenerate it every time

**Comment by larshp** [comment] 2020-05-23 10:27
@manb-msft did above help?

**Comment by manb-msft** [comment] 2020-05-27 06:02
@larshp it does look like some network/firewall issues. They were able to reproduce this behavior outside of abapGit as well. I'll follow up and update this thread.

**Comment by larshp** [comment] 2020-06-12 16:23
@manb-msft any updates?

**Comment by manb-msft** [comment] 2020-06-15 06:02
@larshp sorry about the delay on this one. I've asked the team to provide an update so we can add some notes and close this out. Thanks so much for checking in!

**Comment by larshp** [comment] 2020-09-04 09:51
closing, no progress

**Closed by larshp** 2020-09-04 09:51 UTC
