### ISSUE TITLE
The data object "<LS_OBJECTS>" does not have a component called "UDATE".

### ISSUE THREAD

**Issue by agiguere** [larshp/abapGit#3257] opened 2020-03-12 21:50 UTC
I got an activation error

line 74036
error  The data object "<LS_OBJECTS>" does not have a component called "UDATE".

SAP_ABA 740 012

thanks

**Comment by larshp** [comment] 2020-03-13 05:11
duplicate of https://github.com/larshp/abapGit/issues/3255 ?

**Comment by larshp** [comment] 2020-03-13 10:40
@agiguere try again, latest version, PR is merged

**Comment by agiguere** [comment] 2020-03-13 17:20
thanks

**Comment by larshp** [comment] 2020-03-13 17:43
asumming it works? closing

**Closed by larshp** 2020-03-13 17:43 UTC

**Comment by agiguere** [comment] 2020-03-13 17:57
wait, I am testing it, I download the program from here is it ok 
https://docs.abapgit.org/guide-install.html

**Comment by agiguere** [comment] 2020-03-13 18:16
I confirm the program compile without error, yes you can close this incident, thanks
