### ISSUE TITLE
Error: Overwrite CLAS ZCL_ABAPGIT_TIME undecided

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#3099] opened 2019-12-02 09:33 UTC
When I pull the latest abapGit version in one of my customer systems I get an error 'Overwrite CLAS ZCL_ABAPGIT_TIME undecided'.

![image](https://user-images.githubusercontent.com/17437789/69947082-322f8080-14ed-11ea-8cce-2b1e453cf303.png)
![image](https://user-images.githubusercontent.com/17437789/69946744-8b4ae480-14ec-11ea-8647-2821c7318c85.png)
![image](https://user-images.githubusercontent.com/17437789/69946757-9140c580-14ec-11ea-8da3-175b2ff21d43.png)
![image](https://user-images.githubusercontent.com/17437789/69946906-ce0cbc80-14ec-11ea-99ea-59942b2666b5.png)

LT_OVERWRITE
![image](https://user-images.githubusercontent.com/17437789/69946932-db29ab80-14ec-11ea-8eb6-e440e39c7ac0.png)

vs, IT_OVERWRITE
![image](https://user-images.githubusercontent.com/17437789/69946948-e8469a80-14ec-11ea-9b96-0f258b082b04.png)

There's a difference in the result calculation
![image](https://user-images.githubusercontent.com/17437789/69947293-aa964180-14ed-11ea-88f4-e10e5cba8ca2.png)
![image](https://user-images.githubusercontent.com/17437789/69947342-c26dc580-14ed-11ea-8e77-8b57de484c5f.png)

Workaround: Jump over the raise method in the debugger.

**Comment by sbcgua** [comment] 2019-12-02 10:09
+1, also seen this issue recently with another product. "undecided" classes appear quite randomly. version 1.90.0 so the issue is relatively old.

**Comment by larshp** [comment] 2019-12-02 11:03
worked okay when I pulled it to my dev system.

I dont think there have been any changes recently for this logic, so it might be a bug

**Comment by mariusraht2** [comment] 2019-12-02 19:44
We changed the class in PR #3096 - I renamed the get method to get_unix, added a get_real method and  added unit tests.

**Comment by sbcgua** [comment] 2019-12-02 20:44
Just info: It is certainly older then 3096. I'm using rather old version (~2 month) for current deployments and see these errors. Don't want to change anything now due to stability requirements. This error regularly happens within ~20 classes - every time on another class. Not sure how to reproduce in a predictable way.

**Comment by christianguenter2** [comment] 2019-12-03 11:51
The error was reproducale on that particular system, but is no longer. 
I think too that is has nothing todo with 3096.

**Comment by mariusraht2** [comment] 2019-12-10 15:07
![grafik](https://user-images.githubusercontent.com/45243391/70541308-14a28c80-1b67-11ea-99cf-99ebf0d157eb.png)

**Comment by vonglan** [comment] 2020-03-03 08:22
Same problem here, when Pulling a ZIP of the newest ABAP2XLSX via the newest ZABAPGIT_FULL.

**Comment by mariusraht2** [comment] 2020-04-03 13:58
For me it helped to remove the repo and add it again.

**Comment by timbolski** [comment] 2020-05-03 01:55
> For me it helped to remove the repo (Advance on repo page > Remove) and to add it again. After that I didn't experience this error again. Could someone please confirm this?

Thanks, that resolved the issue for me.

I'm not sure if this helps in replicating the issue.
We upgraded from ECC to S4 and I went to pull updates made on ECC while the upgrade was being done. So I guess that the REPO thought that it was current at a different point in time.

**Comment by mbtools** [comment] 2020-07-15 01:31
This is the same as https://github.com/larshp/abapGit/issues/3550. Fixed by https://github.com/larshp/abapGit/pull/3558.

**Closed by mbtools** 2020-07-15 01:31 UTC
Labels: bug
