### ISSUE TITLE
Cannot activate abapGit

### ISSUE THREAD

**Issue by Angsmann** [larshp/abapGit#1255] opened 2018-03-19 08:08 UTC
Hello,

first of all, thanks a lot for this great project! I've already got to know Git in a web project and I'm looking forward to using it for ABAP as well.
I followed the instructions and created a report named ZABAPGIT and pasted the code.
When I try to activate this report, I get the error message "'OBJ_TYPE' and the line type of "LT_COLUMNS" are incompatible" in line 12757 (the code in this line is INSERT 'OBJ_TYPE' INTO TABLE lt_columns. ).

How can I fix this issue? I don't want to start modifying the abapGit code by myself...

Thanks a lot!
Best regards, Anne

**Comment by larshp** [comment] 2018-03-19 08:12
what SAP version are you running?

guess the code in question is: https://github.com/larshp/abapGit/blob/30112e055705dc3f64e4e7cce4ea7ae46b754573/src/zcl_abapgit_objects.clas.abap#L710

**Comment by Angsmann** [comment] 2018-03-19 08:14
My SAP_BASIS and SAP_ABA are Release 731, SP-Level 0011.

Yes, that's the code in question.

**Comment by larshp** [comment] 2018-03-19 08:22
Thanks, can you help pasting a screenshot of how SAP standard `stringtab` is defined in SE11?

**Comment by Angsmann** [comment] 2018-03-19 08:29
![grafik](https://user-images.githubusercontent.com/16959094/37585025-f19ebcfa-2b57-11e8-99e0-9e38e5ffb194.png)

**Comment by larshp** [comment] 2018-03-19 08:35
hmm, looks good


can you try changing

```INSERT `OBJ_TYPE` INTO TABLE lt_columns.```

to

`INSERT |OBJ_TYPE| INTO TABLE lt_columns.`

and see if it works

**Comment by Angsmann** [comment] 2018-03-19 08:37
Still doesn't work. :-(

![grafik](https://user-images.githubusercontent.com/16959094/37585355-271357f0-2b59-11e8-9624-8be188766aba.png)

**Comment by larshp** [comment] 2018-03-19 08:51
try:

```abap
DATA: lv_str TYPE string.
lv_str = 'OBJ_TYPE'.
INSERT lv_str INTO TABLE lt_columns.
```

I think this will work, it is strange that the previous syntax works in 702 but not 731, but 731 is a strange version in all cases 😄 

Try changing the code manually, to see how big the problem is, and provide a list there, then we will change the abapGit code with this downport.

**Comment by Angsmann** [comment] 2018-03-19 08:58
Thanks, this workaround fixed the issue with lt_columns (I had to do the same with 'OBJ_NAME' in the next line).
Now there's another error - see screenshot. ;-)

![grafik](https://user-images.githubusercontent.com/16959094/37586251-149cf196-2b5c-11e8-96de-d840209ae740.png)

**Comment by Angsmann** [comment] 2018-03-19 09:01
Apparently this error message is related to the bracket in the text here (line 407).
Why is that not allowed!?

![grafik](https://user-images.githubusercontent.com/16959094/37586364-6298e670-2b5c-11e8-8e64-d0047f6d0459.png)

**Comment by larshp** [comment] 2018-03-19 09:06
instead of

```abap
              CALL FUNCTION 'POPUP_TO_INFORM'
                EXPORTING
                  titel = 'Migration has failed'
                  txt1  = lx_exception->get_text( )
```

introduce a local variable, something like the following, this is an issue we seen quite frequently which is also required for 702 downports,

```abap
data lv_text type text200.
lv_text = lx_exception->get_text( ).
              CALL FUNCTION 'POPUP_TO_INFORM'
                EXPORTING
                  titel = 'Migration has failed'
                  txt1  = lv_text
```

**Comment by Angsmann** [comment] 2018-03-19 09:13
Yay, it's working now!
Thanks a lot for your help, Lars! :-)

**Comment by larshp** [comment] 2018-03-19 09:15
cool, the above changes will be incorporated into the abapGit souce code, we'll keep the issue open until this is merged

many of us doing development do not have access to lower versions than 740, so thanks for testing

Also see https://github.com/larshp/abapGit/issues/1243 some of the issues above will fix some of the 702 issues

**Comment by Angsmann** [comment] 2018-03-19 09:20
Perfect!
I also have access to another system which has Release 7.02 (Level 0011). When I have time, I'll also install abapGit there and have a look at #1243 for help.
Thanks again!

**Comment by larshp** [comment] 2018-03-19 16:20
thanks @christianguenter2 for the fix

I'll close this issue, @Angsmann feel free to open a new issue if you find anything on 702 or there are other issues on 731

**Closed by larshp** 2018-03-19 16:20 UTC
Labels: bug
