### ISSUE TITLE
Generated maintenance view: Dynpro cannot be created on import

### ISSUE THREAD

**Issue by mrsimpson** [larshp/abapGit#501] opened 2016-12-13 18:43 UTC
Imported the attached ZIP to a new offline repo (in new system).
It contains a maintenance view (` expert_finder\zp2ph_maint.fugr* `).
[ZP2P_20161213_141403.zip](https://github.com/larshp/abapGit/files/649806/ZP2P_20161213_141403.zip)
Import fails due to an error importing it (unfortunately, I don't have the error message at hand and I cannot reproduce it now due to changes I've done manually).

**Comment by larshp** [comment] 2016-12-13 18:48
thanks for the bug reports 😄

**Comment by mrsimpson** [comment] 2016-12-16 08:37
no worries.
Just created an online-repository and confirm the sam issue.
Debugged a bit:
```DESERIALIZE_DYNPROS (LCL_OBJECTS_PROGRAM)

RPY_DYNPRO_INSERT

                                   	MSGID	                                   	XI
                                   	MSGTY	                                   	E
                                   	MSGNO	                                   	166
                                   	MSGV1	                                   	Table ZP2PH_EXP_AREA not active in ABAP
                                   	MSGV2	                                   	 Dictionary
```
=> TABLEs need to be activated prior to _deserializing_ the dynpro

**Comment by mrsimpson** [comment] 2016-12-31 13:01
Can be reproduced with https://github.com/mrsimpson/abapgit-view/tree/master

**Comment by larshp** [comment] 2016-12-31 13:19
proposed solution: #511

**Comment by mrsimpson** [comment] 2016-12-31 13:25
agreed. ddic really has to be activated. Changig sequence of serialization in `prioritize_deserialization` is not sufficient.

**Comment by larshp** [comment] 2017-01-04 17:36
try again, should end up with the same issue as described in https://github.com/larshp/abapGit/issues/305

so we can close this issue if you get the error from #305

**Comment by larshp** [comment] 2017-01-29 10:31
closing, feel free to open a new issue if the problem is not fixed

**Closed by larshp** 2017-01-29 10:31 UTC
Labels: bug

**Comment by mrsimpson** [comment] 2017-01-31 05:28
Confirmed. There seems to be another issue still, but I'll open another bug for that

**Comment by larshp** [comment] 2017-01-31 05:30
same error as #305 ?

**Comment by mrsimpson** [comment] 2017-01-31 07:25
Yup. Nasty one
