### ISSUE TITLE
Stage shown right after Pull

### ISSUE THREAD

**Issue by nununo** [larshp/abapGit#318] opened 2016-09-05 11:29 UTC
Hi,

Right after doing Pull to abapGit I get a file with a diff and the button "Stage" there:

![image](https://cloud.githubusercontent.com/assets/532049/18246560/41e54f10-7364-11e6-8062-f882b3e4c193.png)

And this is the diff:

![image](https://cloud.githubusercontent.com/assets/532049/18246572/5c419dc8-7364-11e6-80b8-c7f639f5faf3.png)

**Comment by larshp** [comment] 2016-09-05 11:34
the diff and stage links are visible when the remote and local objects does not match 100%. In this case the RSTAT field does not match.

Guess the initial ZABAPGIT report was created with RSTAT = T. The field should be overwritten when doing the pull, this looks like a bug in abapGit

**Comment by larshp** [comment] 2016-09-05 11:43
@nununo try again

note that the pull has to be done with the latest version of abapGit, so if pulling latest version of abapGit with abapGit will just install the fix, not run the fix

**Comment by nununo** [comment] 2016-09-05 11:50
I'm not sure I got it right. The problem is still there:

What I did:
- I pulled
- /N SE38 ZABAPGIT to run the latest version
- The problem was still there

So I decided to click on the link at the very top which said something like "Get abapgit" (and which no longer appears). It fetched a lot of files, which I then activated and now I have several new files which I didn't have before, all unstaged:

![image](https://cloud.githubusercontent.com/assets/532049/18246972/4ed420e0-7367-11e6-90a6-6bfc184acdf0.png)

**Comment by larshp** [comment] 2016-09-05 11:57
looks like the objects from "abapGit-plugins" was installed into the wrong package. Just tried the button, and could not reproduce the issue.

You can delete the objects with "new" manually to clean up the mess(sorry). And goto "Advanced -> Uninstall" under the "abapGit-plugins" to remove the plugins

**Comment by larshp** [comment] 2016-09-05 12:01
note that the pull of abapGit has to be done with the latest abapGit, to see that the issue is fixed

you can force a pull via "Advanced -> Reset local"

**Comment by nununo** [comment] 2016-09-05 12:12
Got it. no more diff.

But... regarding those abapGit-plugins objects...

Here's what I did:
- Deleted all of them (but please note that they were in the right package!)
- abapGit was now looking ok
- abapGit-plugins started showing errors
- I did an Advanced->Reset local in abapGit-plugins
- All the objects were created again, in the right package, as you can see
in the screenshot
- The abapGit-plugins now looks fine
- But the abapGit repository is again showing all those files as new and
unstaged

[image: Inline image 1]

**Comment by larshp** [comment] 2016-09-05 12:15
is $ABAPGIT_PLUGINS a subpackage of $ABAPGIT in your system?

**Comment by nununo** [comment] 2016-09-05 12:18
Yes, as you can see in the screenshot I sent you before.

**Comment by nununo** [comment] 2016-09-05 12:19
I guess the image was not sent since I replied by email:
![image](https://cloud.githubusercontent.com/assets/532049/18247624/5d46ad10-736b-11e6-90d8-fc057c7eaaf5.png)

**Comment by larshp** [comment] 2016-09-05 12:21
okay, you changed the superpackage manually

change super package of $ABAPGIT_PLUGINS to $DEVTOOLS and the issue should be fixed for you


Both $ABAPGIT and $ABAPGIT_PLUGINS are created with $TMP as superpackage when clicking the "get abapgit button". A repository includes the subpackages in the object list, to simulate folder structure

**Comment by nununo** [comment] 2016-09-05 12:27
Done. Thanks! Seems to work now. I don't remember having put $ABAPGIT_PLUGINS as subpackage of $ABAPGIT but probably did it :p

**Comment by larshp** [comment] 2016-09-05 12:28
or perhaps it is a bug in abapGit, I've tried reproducing but no success

**Comment by nununo** [comment] 2016-09-05 12:29
There is another similar issue, though:

After my pull request I removed my fork and cloned your abapGitServer repository. But I get differences and the stage button. Even after I did and Advanced->Reset local:

![image](https://cloud.githubusercontent.com/assets/532049/18247805/91c2b72c-736c-11e6-879b-3b74532b0955.png)

And here are the differences down at the bottom:

![image](https://cloud.githubusercontent.com/assets/532049/18247837/d2a017d0-736c-11e6-9403-a4609d08754e.png)

**Comment by larshp** [comment] 2016-09-05 12:35
SICF: there might be a bug here, but nothing important

TABL: I have developed abapGitServer on 750, so the meta data from 750 is saved in the xml files. When importing on 731(?) it has less meta data, so there is a difference in the xml files, which cannot easily be avoided.

When staging changes just pick the objects you have changed. Or just submit everything, it doesnt matter if the 750 meta data is overwritten, as it handles the new meta data as optional/defaults values.

**Comment by nununo** [comment] 2016-09-05 12:36
I see. Makes sense. Thanks.

**Comment by nununo** [comment] 2016-09-05 12:36
I guess we can close this issue then, right?

**Comment by larshp** [comment] 2016-09-05 12:36
yeah, closing

**Closed by larshp** 2016-09-05 12:36 UTC
