### ISSUE TITLE
Stage and commit only one or more files if java sap gui was used

### ISSUE THREAD

**Issue by nimble-123** [larshp/abapGit#790] opened 2017-06-14 12:01 UTC
I have a dev package tracked by abapGit with one repo.

Imagine in this dev package are several objects, i change some of them and want to stage and commit the changes.

Now if i only stage one of the changed objects and want to click "Commit (1)" i get the error "process_stage_list: empty list"

If i click "Add all and commit (47)" everything works as expected.

**Comment by sbcgua** [comment] 2017-06-14 12:52
@nlsltz  is the issue reproducable ?
Can you attach a screenshot ? and debug info (Advanced -> debug info) pls ?
Also does the stage page display something like this at the bottom right ?

![image](https://user-images.githubusercontent.com/15635498/27132990-649f65a2-5119-11e7-9d79-4c2268794514.png)

**Comment by nlsltz** [comment] 2017-06-14 12:57
@sbcgua yes it is reproducable.

![screenshot at juni 14 14-56-24](https://user-images.githubusercontent.com/1546954/27133217-bd4a2050-5111-11e7-82ae-7e892a7d9c84.png)
![screenshot at juni 14 14-55-52](https://user-images.githubusercontent.com/1546954/27133218-bd4aebde-5111-11e7-8f0b-4442db937489.png)
![screenshot at juni 14 14-55-30](https://user-images.githubusercontent.com/1546954/27133216-bd469750-5111-11e7-93d6-f55d8b973e99.png)

**Comment by sbcgua** [comment] 2017-06-14 13:09
Hmmm interesting ... maybe that's because of namespaces ? ...

Could you pls send "Advanced -> Debug info" screenshot also ?
And the source of stage page HTML (just save it with right button -> view html - and zip - github will not allow attaching bare html)

**Comment by nlsltz** [comment] 2017-06-14 13:16
Found something interessting. The issue only appears if i use the JAVA SAP GUI, just logged in with windows sap gui and there i am able to just stage and commit one file.

anyhow here are the screenshots

<img width="1035" alt="screenshot at juni 14 15-12-07" src="https://user-images.githubusercontent.com/1546954/27133961-4caf34b8-5114-11e7-80a6-89bdfba6bf10.png">
[stage_site.html.zip](https://github.com/larshp/abapGit/files/1074668/stage_site.html.zip)

**Comment by sbcgua** [comment] 2017-06-14 13:28
Yeah, that was my suspicion actually :)
JAVA GUI may restrict JS a lot more than regular GUI (especially on Mac - are you on Mac ? :)

**Comment by nlsltz** [comment] 2017-06-14 13:30
yes i am on macOS :) so if it is a problem of the java sap gui we could close this issue as we are not able to fix it, right?

**Comment by sbcgua** [comment] 2017-06-14 13:52
Well, I maybe will some day ... :) I also have mac which I sometimes (rarely though) use for SAP work. So it will keep reminding me about the issue.
It is not clear by the way what kind of browser is used there ... 
Let's keep the issue for a while, I'll try to check it on the weekend if I have time.

**Comment by Sdfraga** [comment] 2017-09-24 18:02
Hello,

I am having the same issue.
I am also using SAP Java Gui with a MacOS

**Comment by jhodel-vesta** [comment] 2017-11-23 13:20
I'm having the same issue too.. same JAVA GUI on macOS

**Comment by mtuli0** [comment] 2018-04-19 13:30
Same issue with JAVA GUI on Ubuntu

**Comment by larshp** [comment] 2018-04-19 13:52
thanks, reproducing on Ubuntu might be easier for me than macOS

**Comment by mtuli0** [comment] 2018-04-19 13:54
@larshp : is there a guide for contributing to this project? I would like to

**Comment by larshp** [comment] 2018-04-19 18:50
@mtuli0 see https://github.com/larshp/abapGit/blob/master/CONTRIBUTING.md plus feel free to join the Slack channel for more info/questions, https://abapgit-slackinviter.herokuapp.com/

**Comment by bigld** [comment] 2018-09-05 20:28
This is a bug in SAP standard with Java GUI - at least on macOS, not tested on other OS
Dynamic generated form fields are not used by the gui control, although they are sent by the browser.
The generated form is ok!

We could create the form "static" in ZCL_ABAPGIT_GUI_PAGE_STAGE and also add some more checks in ->process_stage_list?


A copy of SAP standard report SAPHTML_EVENTS_DEMO with test html/javascript can be found here:
https://github.com/bigld/abapgit_issues_790.git

Java GUI uses the ICE Browser: https://help.sap.com/doc/saphelp_nw75/7.5.5/en-US/4d/77a65efe472b8ae10000000a42189b/frameset.htm

**Comment by bigld** [comment] 2018-09-07 18:01
same as #1866

**Comment by jfilak** [comment] 2018-09-14 12:18
Reported to SAP GUI for Java developers.

**Comment by marcellourbani** [comment] 2018-09-18 09:10
have a [working POC](https://github.com/marcellourbani/abapGit/tree/issue_%231866_%23790_hack_for_java_sapgui)

tested on linux with 7.51 backend

**Comment by larshp** [comment] 2019-10-07 08:46
try again, guess this was solved as part of https://github.com/larshp/abapGit/pull/2873 ?

**Comment by marcellourbani** [comment] 2019-10-07 23:48
Works fine now, thanks guys

**Closed** 2019-10-08 02:09 UTC
Labels: bug
