### ISSUE TITLE
FUGR: Settings not adapted after change on git repo

### ISSUE THREAD

**Issue by ThomasPloski** [larshp/abapGit#1601] opened 2018-07-09 07:25 UTC
Hi community,

I have figured out the issue that settings or description is not changed in local system in case of the object already exists.

See the following code snippit in method deserialize_xml:

    CALL FUNCTION 'RS_FUNCTION_POOL_INSERT'
      EXPORTING
        function_pool           = lv_group
        short_text              = lv_stext
        namespace               = lv_namespace
        devclass                = iv_package
        unicode_checks          = lv_abap_version
      EXCEPTIONS
        name_already_exists     = 1
        name_not_correct        = 2
        function_already_exists = 3
        invalid_function_pool   = 4
        invalid_name            = 5
        too_many_functions      = 6
        no_modify_permission    = 7
        no_show_permission      = 8
        enqueue_system_failure  = 9
        canceled_in_corr        = 10
        undefined_error         = 11
        OTHERS                  = 12.
    IF sy-subrc <> 0 AND sy-subrc <> 1 AND sy-subrc <> 3.
      zcx_abapgit_exception=>raise( 'error from RS_FUNCTION_POOL_INSERT' ).
    ENDIF.

**Comment by timbolski** [comment] 2018-07-21 09:10
We are also having this issue, though it look like an auth error at this stage. We were getting rc = 7.
We have requested the correct authorisations. I will update once we receive the requested auth.

**Comment by timbolski** [comment] 2018-07-21 09:29
Hi Lars,

                  When we are trying to Pull into a customer system, we get the message RS_FUNCTION_POOL_INSERT

We originally loaded a couple of objects through a transport as we couldn’t seem to get anything to load into our namespace.

 

Debug showed us RC 7 so we ran SU53 and got this. We have submitted this to get the auths. We probably won’t hear back on it until Monday now.

 

Tim

**Comment by larshp** [comment] 2018-07-21 09:34
Pull request https://github.com/larshp/abapGit/pull/1667 opened, so it will show the error code instead of having to debug

**Comment by christianguenter2** [comment] 2018-07-21 10:03
SE80 directly updates TRDIR and TLIBT.
Program SAPLSEUF / LSEUFF07
FORM GROUP_CHANGE

**Comment by christianguenter2** [comment] 2018-07-21 15:53
> I have figured out the issue that settings or description is not changed in local system in case of the object already exists.

Couldn't reproduce for settings. Do you have an example?

**Comment by christianguenter2** [comment] 2018-07-22 08:01
@ThomasPloski 
Can you check the latest build? Description should be working now.

**Comment by larshp** [comment] 2018-07-28 05:31
@ThomasPloski

**Comment by larshp** [comment] 2018-08-07 05:39
closing

**Closed by larshp** 2018-08-07 05:39 UTC
Labels: bug
