### ISSUE TITLE
xml-container: reading data 

### ISSUE THREAD

**Issue by mrsimpson** [larshp/abapGit#171] opened 2016-02-17 17:50 UTC
When reading data from the XML-container, only the data is returned.
(read_table, read_strucure, element_read)

This is not sufficient in case the type of the system to which is being imported deviates from the source system, as the consumer is not easily able to create a work area / data reference of the type.

**Comment by larshp** [comment] 2016-02-17 19:52
Guess this is needed for the generic object approach? Wouldn't it know the table types beforehand?

**Comment by mrsimpson** [comment] 2016-02-17 20:18
sure it does. In the generic approach, I persist the table metadata along with the actual data.
But also for other plugins, this might be necessary. Think of an API structure being enhanced with an additional field in a new release.

**Comment by larshp** [comment] 2016-05-06 07:59
hi, I tried reproducing the issue in unit test with above commit, but no luck. Can you help reproducing the issue?

**Comment by larshp** [comment] 2016-05-31 13:45
closing issue, unable to reproduce. Reopen or create new issue if issue still exists

**Closed by larshp** 2016-05-31 13:45 UTC
