### ISSUE TITLE
todo, WEBI, function name

### ISSUE THREAD

**Issue by timbolski** [larshp/abapGit#1974] opened 2018-09-28 13:21 UTC
When trying to pull sometimes I am getting this error todo, WEBI, function name. No other help is available on the message.

![image](https://user-images.githubusercontent.com/4916003/46210781-48c7ce00-c364-11e8-9d5c-6b5e4c7fda59.png)

Currently using 1.77.0 in the system doing the pull.

**Comment by christianguenter2** [comment] 2018-09-28 13:34
@timbolski any chance to provide a public repo to reproduce this?

**Comment by timbolski** [comment] 2018-09-28 13:39
I have added you as a collaborator to the private repo.
https://github.com/timbolski/-ZPM-WO2PDF2/invitations

**Comment by timbolski** [comment] 2018-09-28 13:40
Also, it seems if I run the PULL twice, it short dumps the second time around.

**Comment by christianguenter2** [comment] 2018-09-28 13:47
Doesn't work because I cannot access namespace /ZPM/ in my system. Maybe you can prepare a slim repo in Z-namespace?

**Comment by timbolski** [comment] 2018-09-28 14:12
Ok, Please try this one
https://github.com/timbolski/ZTESTWEBI
Package is ZTESTWEBI

**Comment by larshp** [comment] 2018-09-28 14:15
created https://github.com/abapGit-tests/WEBI, we can store the example there for future automatic tests

**Comment by timbolski** [comment] 2018-09-29 02:06
@christianguenter2 I have added a second Web Service.

**Comment by christianguenter2** [comment] 2018-09-29 07:36
@timbolski that wasn't what I meant. We need a second entry for PVEPFUNCTION  
https://github.com/timbolski/ZTESTWEBI/blob/d1352e7cea7c84417455a26a6e8abdd02a31541a/src/ztestwebi.webi.xml#L14-L22

compared to your original repo
https://github.com/timbolski/-ZPM-WO2PDF2/blob/9e3165545e098423fa37a57e541be8d67f4f2784/%23zpm%23wo2pdf2.webi.xml#L15-L30

**Comment by timbolski** [comment] 2018-09-29 22:48
@christianguenter2 I have added another which now has 2 PVEPFUNCTIONs.

**Comment by timbolski** [comment] 2018-09-30 09:44
Thanks for the awesome help guys. I have requested for the client to import the fix and then I can verify.

**Comment by christianguenter2** [comment] 2018-09-30 10:01
@timbolski please note that the fix is not yet merged into master.

**Comment by christianguenter2** [comment] 2018-10-08 18:36
@timbolski does it work?

**Comment by timbolski** [comment] 2018-10-08 22:28
Yes, it does!

**Comment by larshp** [comment] 2018-10-09 04:14
thanks, closing

**Closed by larshp** 2018-10-09 04:14 UTC
Labels: bug
