### ISSUE TITLE
Error: Implementation missing for method "ZIF_ABAPGIT_OBJECT~GET_DESERIALIZE_STEPS"

### ISSUE THREAD

**Issue by enot-poloskun** [larshp/abapGit#2497] opened 2019-03-12 12:24 UTC
Hi Guys,

I am trying to implement the actual version of ZABAPGIT_FULL Program. I am receiving the following Error.

Implementation missing for method "ZIF_ABAPGIT_OBJECT-GET_DESERIALIZE_STEPS". "ZIF_ABAPGIT_OBJECT-GET_DESERIALIZE_STEPS".

Lack of implementation of this method do not allow me to activate the imported objects.
This method is used in class ZCL_ABAPGIT_OBJECTS->deserialize

Could you please help me or provide the correct version of the programm?

Thanks in advance and best regards
Denis

**Comment by dbon** [comment] 2019-03-12 12:31
I can confirm that this syntax error exists in the latest build. 

https://raw.githubusercontent.com/abapGit/build/master/zabapgit.abap

**Comment by larshp** [comment] 2019-03-12 13:02
thanks, I will take a look

**Comment by larshp** [comment] 2019-03-12 13:07
Looks like its a warning in a global class but an error for local classes, way will be implementing https://github.com/larshp/abapGit/issues/2493

**Comment by larshp** [comment] 2019-03-12 13:16
as a temporary workaround, you can get one of the older versions from https://github.com/abapGit/build

eg. https://github.com/abapGit/build/blob/05af5660cea9b43c95b4116c6ca4a53ccc7e4ad8/zabapgit.abap

**Comment by enot-poloskun** [comment] 2019-03-12 13:26
Thanks a lot for an older version!

**Comment by larshp** [comment] 2019-03-12 14:42
@enot-poloskun try again, latest version, https://github.com/larshp/abapGit/pull/2499 merged

**Closed** 2019-03-13 14:53 UTC
Labels: bug
