### ISSUE TITLE
ITAB_DUPLICATE_KEY Shortdump while importing OpenSAP offline repo

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#2904] opened 2019-09-02 18:40 UTC
A shortdump occurs when this OpenSAP offline repo is imported to a local package. No problem with Z-Package.
ZIP file from here:
https://open.sap.com/courses/wtc1/items/5poy1IKePw8Tzv1rBc66cz 

![image](https://user-images.githubusercontent.com/17437789/64130275-9beea000-cdc1-11e9-940c-f5bf09683d71.png)
![image](https://user-images.githubusercontent.com/17437789/64130274-9abd7300-cdc1-11e9-8442-6cf5671732a0.png)
![image](https://user-images.githubusercontent.com/17437789/64130307-d35d4c80-cdc1-11e9-83e1-01c71e0132bd.png)

**Comment by marcellourbani** [comment] 2019-10-09 08:12
Looks like the issue is that local packages have no object directory entry
![image](https://user-images.githubusercontent.com/2453277/66462980-0dcaa100-ea74-11e9-8c26-33ba9742f883.png)
Also applies for those created in SE80. Plan to fix by trying the package table if tadir fails and the package is local

**Comment by larshp** [comment] 2019-10-09 08:21
Installing something like https://github.com/abapGit-tests/DTEL to a local package works without problems

**Comment by marcellourbani** [comment] 2019-10-09 09:23
Will have a look.
Have a fix on my home box already, but want to find out why this doesn't have the issue.
Does your local package have a TADIR entry?

**Comment by larshp** [comment] 2019-10-09 09:46
no, no local packages have TADIR entries

**Comment by marcellourbani** [comment] 2019-10-09 12:18
Funny, works for me too.
Afraid I forgot to update abapgit before trying (was just a few days behind)

![image](https://user-images.githubusercontent.com/2453277/66480706-28fad800-ea97-11e9-95c4-9da81e0f052e.png)
I think you can close this unless @christianguenter2  has objections

**Comment by christianguenter2** [comment] 2019-10-09 12:25
Hm, still doesn't work for me.

**Comment by marcellourbani** [comment] 2019-10-09 22:07
Very weird.
I deleted and recreated the package and now is dumping again with the course file, while it works with DTEL
PR will follow

**Closed** 2019-10-12 11:00 UTC
Labels: bug
