### ISSUE TITLE
unpack not ok - when adding 2 identical abap files at the same time

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#288] opened 2016-07-09 10:10 UTC
![image](https://cloud.githubusercontent.com/assets/5888506/16707444/1ad72f6a-45ce-11e6-8923-e69412fbae57.png)

where the 2 reports contain exactly the same ABAP code

**Comment by flaiker** [comment] 2017-10-28 11:14
This just happened to me. Seems to be reproduceable when two `package.devc.xml` are to be committed at the same time. Though this not happen on the initial DEVC introduction which is weird to me.

![image](https://user-images.githubusercontent.com/5270359/32133919-c06f7dc6-bbe1-11e7-88e5-0801a5b25f4f.png)
![image](https://user-images.githubusercontent.com/5270359/32133923-d03bdccc-bbe1-11e7-9971-e669d0d9ef3f.png)

**Comment by larshp** [comment] 2017-10-29 07:48
@flaiker can we open this as a separate issue?

**Comment by flaiker** [comment] 2017-10-29 13:28
Sure

**Closed by flaiker** 2017-10-29 13:28 UTC
