### ISSUE TITLE
ABAPGit repo - all files constantly modified

### ISSUE THREAD

**Issue by fsh8** [larshp/abapGit#1044] opened 2017-11-06 12:27 UTC
Hi, 

Not sure if that is the cause, but on a non-unicode system all the files keep the status 'modified' even after a pull. The difference highlighted is a hashtag (#) on the remote repo in the first line of the xml.

![abap git modif](https://user-images.githubusercontent.com/33420738/32441078-2a5c1148-c2f6-11e7-9b2c-7e898f3a9e62.png)

**Comment by larshp** [comment] 2017-11-06 12:54
it is most likely a byte order mark, see https://github.com/larshp/abapGit/issues/799

**Comment by fsh8** [comment] 2017-11-06 14:14
I will take a look, thanks.
M.

**Comment by JohannesKonings** [comment] 2018-08-14 18:00
I've found no solution to prevent BOM on a unicode system. 
So I delete the BOM afterwards:

![image](https://user-images.githubusercontent.com/14806640/44109030-4f70b81a-9ffc-11e8-84e8-b6d22305097a.png)

After the first small tests, this seems to work between unicode and non unicode systems.

**Comment by BlackmanCC** [comment] 2019-10-04 13:10
I am using abapGit on a non-unicode system facing the same issue. alle files are constantly shown as modified. Is there a solution general for this problem? I would also be happy about a fix that I can implement in my fork.

**Comment by larshp** [comment] 2019-10-04 13:26
"I think we should change the code so abapGit does not add byte order marks to any of the xml files"

however it will probably cause a lot of changed files in the ecosystem, so perhaps hide it behind a setting as a starting point

**Comment by larshp** [comment] 2019-10-04 13:36
or perhaps its less invasive to always add it, hmm

**Comment by larshp** [comment] 2019-10-07 06:50
I'll do the change to always add the byte order mark, this is the least invasive on the ecosystem

**Comment by larshp** [comment] 2019-10-07 07:04
@BlackmanCC can you help testing https://github.com/larshp/abapGit/pull/2947 ?

**Comment by BlackmanCC** [comment] 2019-10-07 07:36
Sure, I can test it. Today will be difficult, because I am on the way to TechEd, but I will have some time the next days.

**Comment by BlackmanCC** [comment] 2019-10-14 07:57
The changes of #2947 adding the BOM seem to work. In the diff screen there are no changes shown anymore.  The problem is, that even after updating local checksums, all files are shown as modified.
Maybe it is the same problem as in #2124. 
I suppose that it has to do with calculation of the checksums for local objects that could be different in non-unicode systems . What do you think?

**Comment by larshp** [comment] 2019-10-14 08:09
seems like something is missing somewhere, the screenshots did not show the expected behavior

**Comment by BlackmanCC** [comment] 2019-10-14 08:14
I would really like to solve the problem but do not know where to look at in debugging and where to start. I only see that the rsa1 checksums of local and remote are different even the coding seems to be the same.

**Comment by BlackmanCC** [comment] 2019-10-14 09:30
btw: We encountered the same problems with our internal git system (Gitblit). The fixes of #2947 adding the bom solved the problems for us for the internal system.

**Comment by BlackmanCC** [comment] 2020-01-24 15:12
If anybody has the same problems on a non-unicode system please test the cod ein pull-request #3167 .

**Comment by BlackmanCC** [comment] 2020-01-24 15:12
@JohannesKonings If you still have the same problems on a non-unicode system please test the code in pull-request #3167 .

**Comment by JohannesKonings** [comment] 2020-03-07 18:17
@BlackmanCC thanks, but now we have unicode systems.

**Comment by larshp** [comment] 2020-03-07 18:28
will close the issue, fix merged in https://github.com/larshp/abapGit/pull/3167

**Closed by larshp** 2020-03-07 18:28 UTC
Labels: bug
