### ISSUE TITLE
IATU: The ASSERT condition was violated for ITS templates

### ISSUE THREAD

**Issue by ttulja** [larshp/abapGit#2637] opened 2019-04-17 08:31 UTC
Hi,

I am moving objects to GIT repository using ZABAPGIT. While I commit HTML files of ITS templates, dump is raised in PROCESS_STAGE_LIST method at line 49369. ZABAPGIT has been last updated on 16 APR 2018.
How can I resolve this?

Thanks.

**Comment by larshp** [comment] 2019-04-17 08:37
What is the error message?

**Comment by ttulja** [comment] 2019-04-17 08:47
The ASSERT condition was violated ----- as short text in dump

**Comment by larshp** [comment] 2019-04-17 09:00
^sorry I read "16 APR 2019", not "16 APR **2018**"

update to latest version

**Comment by ttulja** [comment] 2019-04-17 09:04
Will this new version supports ITS templates

**Comment by ttulja** [comment] 2019-04-17 09:06
Can you send me the link to update the latest version of ZABAPGIT

**Comment by larshp** [comment] 2019-04-17 09:08
https://docs.abapgit.org/guide-upgrade.html

**Comment by ttulja** [comment] 2019-04-17 10:50
Hi,
I have coiped the latest version of ZABAPGIT. While committing HTML files it is not raising dump now but throws below error.
![image](https://user-images.githubusercontent.com/49712221/56282314-7de31480-612c-11e9-976d-f4f1cbb28460.png)

Thanks.

**Comment by larshp** [comment] 2019-04-17 10:53
any special characters part of the filename?

**Comment by larshp** [comment] 2019-04-17 11:08
are you using SAP GUI for Java?

**Comment by ttulja** [comment] 2019-04-17 11:14
> any special characters part of the filename?

Filename is like 
/src/itsserivename 99 htmlfile.iatu.html

**Comment by ttulja** [comment] 2019-04-17 11:38
> are you using SAP GUI for Java?

We are not using SAP GUI for JAVA

**Comment by larshp** [comment] 2019-04-17 11:57
do you have multiple services with the same service name?

**Comment by ttulja** [comment] 2019-04-17 11:59
No ITS service names are unique

**Comment by larshp** [comment] 2019-04-19 09:25
unable to reproduce, see example in https://github.com/abapGit-tests/IARP_IASP_IATU/tree/master/src

**Comment by ttulja** [comment] 2019-04-19 11:37
How did you move IATU files to GIT, can you let me know the process

**Comment by larshp** [comment] 2019-08-08 05:10
closing, unable to reproduce

**Closed by larshp** 2019-08-08 05:10 UTC
