### ISSUE TITLE
Shortdump after upgrading to 1.17.9

### ISSUE THREAD

**Issue by grahamrobbo** [larshp/abapGit#325] opened 2016-09-07 05:50 UTC
TYPE_NOT_FOUND exception during `lcl_tlogo_bridge->constructor`.

Seems to be caused by entries in table OBJSL that cannot be passed into `cl_abap_structdescr=>describe_by_name`

I find I have others in my customers' system....
![image](https://cloud.githubusercontent.com/assets/1305633/18301123/6f113c10-7512-11e6-9c04-ae9eeddd4cc8.png)
The exception occurs when I hit the first LIMU DOCU row.

I am currently getting around this by modifying the select statement like this...
```
    SELECT * FROM objsl INTO CORRESPONDING FIELDS OF TABLE mt_object_table
      WHERE objectname = mv_object
      AND   objecttype = co_logical_transport_object
      AND tobject = 'TABU'.

```
.....that is adding the `AND tobject = 'TABU'` to the where clause - but I don't know if this is a good long term way to do this.

**Comment by larshp** [comment] 2016-09-07 06:46
looks like the error occurs down in abapGit-plugins,
https://github.com/larshp/abapGit-Plugins/blob/29b304b360cdc852adc24f9561867acb6f33b9c9/zcl_abapgit_object_by_sobj.clas.locals_def.abap

looks like IWOM = SAP Gateway: Model Metadata, which I have not tested. @mrsimpson can you help?

Alternatively if you uninstall abapGit-Plugins, the program will not dump, and IWOM will show up as unsupported

**Comment by mrsimpson** [comment] 2016-09-07 06:58
I will. Probably considered this as inconsistent metadata. @grahamrobbo: this fix is most probably fine. Can you tell me which other tobject-items exist in objsl for IWOM?
Currently, I can reproduce it.

**Comment by grahamrobbo** [comment] 2016-09-07 07:03
That screenshot is the complete IWOM list in my customer system. So all I see are R3TR-TABU & LIMU-DOCU.

**Comment by larshp** [comment] 2016-09-16 15:11
try again, reproduced in 7.50 system, suggestion `AND tobject = 'TABU'.` added in the code

https://github.com/larshp/abapGit-Plugins/commit/3d22e5e97a58e5e371644667b4ebedea488e1dec

**Comment by mrsimpson** [comment] 2016-09-16 15:38
Thx. Currently don't shave a system at hand to fix it. I'm a bit worried about metadata-consistency-check: I compare object definition in order to detect incompatible changes. Don't know what would happen if you exported an object without the restriction and then import it into a system including the restriction.

**Comment by larshp** [comment] 2016-09-16 15:49
I think currently only support for table content is implemented in the SOBJ plugin, the DOCU would be a different object that could be implemented

**Comment by larshp** [comment] 2016-09-20 06:02
closing issue,  code updated as suggested

**Closed by larshp** 2016-09-20 06:02 UTC
