### ISSUE TITLE
Export of function groups fails for non-english objects

### ISSUE THREAD

**Issue by mrsimpson** [larshp/abapGit#182] opened 2016-02-26 09:11 UTC
```abap
  METHOD serialize_xml.
    DATA: lo_xml      TYPE REF TO lcl_xml,
          lt_functab  TYPE ty_rs38l_incl_tt,
          lt_includes TYPE rso_t_objnm,
          lv_areat    TYPE tlibt-areat.


    SELECT SINGLE areat INTO lv_areat
      FROM tlibt
      **WHERE spras = gc_english**
      AND area = ms_item-obj_name.                      "#EC CI_GENBUFF
    IF sy-subrc <> 0.
      _raise 'not found in TLIBT'.
    ENDIF.
```
Particularly in SAP's motherland, there are many companies implemeting in German. Imho, all languages shall be exported which are available

**Comment by larshp** [comment] 2016-02-26 10:21
yep, also see https://github.com/larshp/abapGit/issues/28

My initial thoughts have been:
User A shares open source project with languages E and D.
User B downloads the project to a system where only E is enabled(assumption: language D is ignored or lost, and/or the API calls should fail when loading a text in a language that is not enabled in the system).
User B will now get a "diff" for all objects with D texts, and user B will not be able to contribute back to the project as it will drop the German texts.

I dont have any good ideas on how to solve this, except for adding the texts to special language package files which can optionally be loaded

**Comment by mrsimpson** [comment] 2016-02-26 10:28
How do you come to the assumption that texts in languages which are not enabled are getting lost? I would expect them to be accepted though never used. Of course, having language-files could solve this, but it adds a tremendous amount of complexity.

**Comment by mrsimpson** [comment] 2016-02-26 10:30
btw: Do you knwo where to enable / disable languages?

**Comment by larshp** [comment] 2016-02-26 10:34
try transaction I18N, "I18N Menu" -> "I18N Customizing" -> "I18N System Configuration"

Will have to do some tests, it was just a quick win early in the project, perhaps now is a good time to find a proper solution as the change can be introduced along with "NextGen XML".

**Comment by larshp** [comment] 2016-02-26 13:28
Summary,

For both cases, somehow the master language should be specified? Perhaps add "master language" in a .abapgit file

### A: Export and Import all translations
All translations are serialized and de-serialized.

To be investigated: Does the API calls for the different object types support translations, alternatively the texts can be forced into the tables directly. (ZSAPLINK_PROGRAM method CREATE_TEXTPOOL has a comment, but perhaps there is a workaround)

Pros: easy(when using SOBJ approach)

Cons: some objects will require changes in the serialized XML(now might be a good time to change it)

### B: Files with "language packages"
All object translations for a target language will be serialized to a special file that can will be loaded into the system if the language is active in the system. Perhaps have 1 file per package/folder(when folder support is implemented).

To be investigated: Following function modules looks promising but it will be a lot of work,
function group LXE_OBJ
function group LXE_OBJ_LIST
	function module LXE_OL_SYS_SEL_TADIR
	function module LXE_OBJ_OBJECTS_GET_S
function group LXE_OBJ_GEN looks promising
function module LXE_OBJ_TEXT_PAIR_READ
function module LXE_OBJ_TEXT_PAIR_WRITE

Pros: no changes to non-SOBJ object serialization,
more standard like to add a supplemental language to the system, 
can be added as a feature sometime in the future

Cons: hard work

**Comment by larshp** [comment] 2016-03-05 08:47
I think we can keep this as-is for a while, but remove the requirement that everything should be in english, this will be fixed in #189

**Comment by larshp** [comment] 2016-05-20 10:55
try again

each repository now have a master language, this is the language for which objects will be exported in, and must be imported in

**Comment by larshp** [comment] 2016-06-22 06:40
closing issue, reopen or create new if the problem is still there :smile:

**Closed by larshp** 2016-06-22 06:40 UTC
