### ISSUE TITLE
Exception raised while installation of abapgit -> zcx_abapgit_exception=>raise( 'HTML preprocessor: </head> not found' ).

### ISSUE THREAD

**Issue by roman0701** [larshp/abapGit#2922] opened 2019-09-19 00:39 UTC
With the regular expression the </head> tag is not found and a exception is raised.

```
CLASS zcl_abapgit_gui_html_processor
METHOD patch_html.
...
    CLEAR: ev_html, et_css_urls.

    lv_head_end = find( val = iv_html regex = |{ cl_abap_char_utilities=>newline }?\\s*</head>| case = abap_false ).
    IF lv_head_end <= 0.
      zcx_abapgit_exception=>raise( 'HTML preprocessor: </head> not found' ).
    ENDIF.
```
Please crosscheck the regular exception something is wrong there.

Many thanks

Best regards
Roman

**Comment by larshp** [comment] 2019-09-19 05:00
"installation", while running the 70k lines report, or cloning online repo?
does it work in other cases?

I've tried installing the compiled report, it seems to work okay

**Comment by roman0701** [comment] 2019-09-19 08:46
At installation. Created report zabapgit_full, compiled and run. Directly after that I get the raise exception with the 'HTML preprocessor: </head> not found'
Netweaver version is 7.40 on Windows.

**Comment by larshp** [comment] 2019-09-19 08:48
are you using the latest version from https://raw.githubusercontent.com/abapGit/build/master/zabapgit.abap ?

**Comment by roman0701** [comment] 2019-09-19 09:06
If the version from yesterday is the most current the yes.

**Comment by roman0701** [comment] 2019-09-19 10:14
I have just copied the code again to my system and compiled it again and run. Same result, same exception.

**Comment by larshp** [comment] 2019-09-19 12:00
any authorization problems, check transaction `SU53`

**Comment by roman0701** [comment] 2019-09-19 12:38
I have SAP_ALL this should be ok. The attribute iv_html is filled with the html page. The lv_head_end has value -1 after execution. I could offer teams or teamviewer for a sharing session if helpful.

**Comment by christianguenter2** [comment] 2019-09-19 13:24
Can you supply the content of `iv_html`?

**Comment by roman0701** [comment] 2019-09-19 14:05
Here is the content of IV_HTML from debugger via View content in XML Browser and then right click and display source code:
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=11,10,9,8" />
    <title>abapGit</title>
    <link rel="stylesheet" type="text/css" href="css/common.css">
    <link rel="stylesheet" type="text/css" href="css/ag-icons.css">
    <link rel="stylesheet" type="text/css" href="css/theme-default.css">
    <script type="text/javascript" src="js/common.js"></script>
  </head>
  <body>
    <div id="header">
      <table class="w100"><tr>
        <td class="logo"><a id="abapGitLogo" href="sapevent:abapgit_home"><img src="img/logo" alt="logo"></a></td>
        <td><span class="page_title"> &#x25BA; HOME</span></td>
        <td class="right">
          <div class="nav-container float-right">
            <ul id="toolbar-main">
              <li>
                <a href="sapevent:repo_newonline">+ Online</a>
              </li>
              <li>
                <a href="sapevent:repo_newoffline">+ Offline</a>
              </li>
              <li>
                <a href="sapevent:go_explore">Explore</a>
              </li>
              <li>
                <a href="#">Advanced</a>
                <ul>
                  <li>
                    <a href="sapevent:go_repo_overview">Repository overview</a>
                  </li>
                  <li>
                    <a href="sapevent:go_db">Database util</a>
                  </li>
                  <li>
                    <a href="sapevent:zip_package">Package to zip</a>
                  </li>
                  <li>
                    <a href="sapevent:zip_transport">Transport to zip</a>
                  </li>
                  <li>
                    <a href="sapevent:zip_object">Object to files</a>
                  </li>
                  <li>
                    <a href="sapevent:changed_by">Test changed by</a>
                  </li>
                  <li>
                    <a href="sapevent:go_playground">Page playground</a>
                  </li>
                  <li>
                    <a href="sapevent:go_debuginfo">Debug info</a>
                  </li>
                  <li>
                    <a href="sapevent:go_settings">Settings</a>
                  </li>
                </ul>
              </li>
              <li>
                <a href="#">Help</a>
                <ul>
                  <li>
                    <a href="sapevent:go_tutorial">Tutorial</a>
                  </li>
                  <li>
                    <a href="sapevent:documentation">Documentation</a>
                  </li>
                  <li>
                    <a href="sapevent:changelog">Changelog</a>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </td>
      </tr></table>
    </div>
    <div id="hotkeys" class="info-panel info-panel-fixed" style="display:none">
      <div class="info-title">Hotkeys<div class="float-right"><a class="close-btn" href="#" onclick="toggleDisplay('hotkeys')">&#x274c;</a></div></div>
      <div class="info-hint"><i class="icon icon-exclamation-triangle pad-right" ></i>Close window with '?' or upper right corner 'X'</div>
      <div class="info-list">
        <ul class="hotkeys">
          <li><span class="key-id">n</span><span class="key-descr">Add online repository</span></li>
          <li><span class="key-id">o</span><span class="key-descr">Installed repo list</span></li>
          <li><span class="key-id">p</span><span class="key-descr">Pull</span></li>
          <li><span class="key-id">r</span><span class="key-descr">Refresh repository</span></li>
          <li><span class="key-id">i</span><span class="key-descr">Run code inspector</span></li>
          <li><span class="key-id">d</span><span class="key-descr">Show diffs</span></li>
          <li><span class="key-id">?</span><span class="key-descr">Show hotkeys help</span></li>
          <li><span class="key-id">l</span><span class="key-descr">Show log</span></li>
          <li><span class="key-id">s</span><span class="key-descr">Stage changes</span></li>
          <li><span class="key-id">b</span><span class="key-descr">Switch branch</span></li>
          <li><span class="key-id">u</span><span class="key-descr">Uninstall repository</span></li>
          <li><span class="key-id">x</span><span class="key-descr">abapGit settings</span></li>
        </ul>
      </div>
    </div>
    <div id="hotkeys-hint" class="corner-hint">Press '?' to get keyboard shortcuts list</div>
    <div id="toc">
      <div class="toc_grid">
        <div class="toc_row">
          <table class="w100"><tr>
            <td class="pad-sides"><i class="icon icon-star blue"  title="Favorites"></i></td>
            <td class="pad-sides w100 favorites">
              <span class="grey">No favorites so far. For more info please check <a href="sapevent:go_tutorial">tutorial</a></span>
            </td>
            <td>
              <div class="nav-container float-right">
                <ul><li>
                  <a href="sapevent:overview"><i class="icon icon-bars blue" ></i></a>
                  <div class="minizone"></div>
                  <ul id="toc-all-repos">
                  </ul>
                </li></ul>
              </div>
            </td>
          </tr></table>
        </div>
      </div>
    </div>
    <div class="tutorial">
      <h1>Tutorial</h1>
      <hr>
      <h2>Adding and cloning repos</h2>
      <p><ul>
        <li>To clone a remote repo (e.g. from github) click 
          <a href="sapevent:repo_newonline">+ Online</a>
           from the top menu. This will copy a remote repo to your system.</li>
        <li>To add a local package as a repo click 
          <a href="sapevent:repo_newoffline">+ Offline</a>
           from the top menu. This will track a repo which already exist in
           the system with abapGit. You'll be able to attach it to remote origin
           or just serialize as a zip file</li>
        <li>Go 
          <a href="sapevent:go_explore">Explore</a>
           to find projects using abapGit</li>
      </ul></p>
      <h2>Repository list and favorites</h2>
      <p><ul>
        <li>To choose a repo press <i class="icon icon-bars blue" ></i> at the favorite bar.</li>
        <li>To favorite a repo click <i class="icon icon-star darkgrey" ></i> icon at repo toolbar.</li>
      </ul></p>
      <h2>abapGit repository</h2>
      <p><ul>
        <li>
          <a href="sapevent:abapgit_install">install abapGit repo</a>
           - To keep abapGit up-to-date (or also to contribute) you need to
          install it as a repository.
        </li>
      </ul></p>
    </div>
    <div id="footer">
      <a id="abapGitLogo" href="sapevent:abapgit_home"><img src="img/logo" alt="logo"></a>
      <table class="w100"><tr>
        <td class="w40"></td>
        <td><span class="version">1.89.0</span></td>
        <td id="debug-output" class="w40"></td>
      </tr></table>
    </div>
  </body>
  <script type="text/javascript">
    setKeyBindings({  "?" : "showHotkeys" ,  "x" : "go_settings" ,  "s" : "go_stage" ,  "b" : "git_branch_switch" ,  "o" : "go_repo_overview" ,  "r" : "repo_refresh" ,  "p" : "git_pull" ,  "n" : "repo_newonline" ,  "u" : "repo_purge" ,  "d" : "go_diff" ,  "i" : "repo_code_inspector" ,  "l" : "repo_log" });
    var gGoRepoPalette = new CommandPalette(enumerateTocAllRepos, {
      toggleKey: "F2",
      hotkeyDescription: "Go to repo ..."
    });
    var gCommandPalette = new CommandPalette(enumerateToolbarActions, {
      toggleKey: "F1",
      hotkeyDescription: "Command ..."
    });
    confirmInitialized();
  </script>
</html>

**Comment by roman0701** [comment] 2019-09-19 14:07
Sorry, once again as saved file.

[1dfcaf88_0410HTML000001.xml.txt](https://github.com/larshp/abapGit/files/3631635/1dfcaf88_0410HTML000001.xml.txt)

**Comment by christianguenter2** [comment] 2019-09-19 14:14
Strange. It contains the `</head>`-tag. So everything looks good. Can you give us more information about your environment? NW-Version? OS? DB? Codepage?

**Comment by roman0701** [comment] 2019-09-19 14:17
Exactly my problem. I have no idea why it is not working.
SAP_BASIS	740	0004	SAPKB74004	SAP Basis Component
SAP_ABA	740	0004	SAPKA74004	Cross-Application Component
Database MAXDB
OS: Windows
Kernel: 741
Codepage: Unicode

**Comment by christianguenter2** [comment] 2019-09-19 14:44
I think OS Windows is the problem. Can you change `cl_abap_char_utilities=>newline` to `cl_abap_char_utilities=>cr_lf` in line 39712 and try again?

**Comment by christianguenter2** [comment] 2019-09-19 14:48
Try replacing line 39712 with 
`    lv_head_end = find( val = iv_html regex = |</head>| case = abap_false ).
`

**Comment by roman0701** [comment] 2019-09-19 14:52
with this code it works for me. The result is LV_HEAD_END = 469
I can start abapGit now.
Many thanks for the quick support

**Comment by roman0701** [comment] 2019-09-19 15:23
> 
> 
> ~I guess OS Windows is the problem. Can you change `cl_abap_char_utilities=>newline` to `cl_abap_char_utilities=>cr_lf` in line 39712 and try again?~
> 
> Edit: On a second look I think that should make no difference.
I guess OS Windows is the problem. Can you change cl_abap_char_utilities=>newline to cl_abap_char_utilities=>cr_lf in line 39712 and try again?

This was also my first idea. I have tried this before opening the issue :-)

**Comment by sbcgua** [comment] 2019-09-20 04:17
or maybe make it `lv_head_end = find( val = iv_html regex = |({ cl_abap_char_utilities=>newline }|{ cl_abap_char_utilities=>cr_lf })?\\s*</head>| case = abap_false ).`

P.S. strange case - htmls are created using `cl_abap_char_utilities=>newline` ... (at zcl_abapgit_html->render)

**Comment by christianguenter2** [comment] 2019-09-20 09:19
I don't get why the regex fails in this case. Whether it's `newline` or `cr_lf` shouldn't matter anyway as it's optional (`?`) ?

**Comment by sbcgua** [comment] 2019-09-20 09:32
mmm, just a guess - if it is CRLF and it finds LF (new line), then it breaks CRLF at the middle later in the code (didn't recheck).
But it is still strange because even the file attached has just LF (new line) - as intended - so it should really work as planned
![image](https://user-images.githubusercontent.com/15635498/65316408-94d9d700-dba2-11e9-9091-c2e7b8046e9d.png)

**Comment by gepparta** [comment] 2019-10-04 13:13
I have the same issue on my BW 7.40 SP05. 
It seems to be an special characters problem.
Check this Screenshot from Notepad++:
![image](https://user-images.githubusercontent.com/3863263/66209997-093f6a80-e6b9-11e9-865f-bee09d38d0d1.png)

**Comment by gepparta** [comment] 2019-10-09 09:03
I have extended the unit test of class zcl_abapgit_gui_html_processor
and used [christians ](https://github.com/larshp/abapGit/issues/2922#issuecomment-533166164)fix in it. PR is on the way. 
But what I can already see in my BW 7.40 SP05 system that some test methods are failing:

![image](https://user-images.githubusercontent.com/3863263/66467190-568a5600-ea84-11e9-9989-7ea95a5b54a8.png)

**Comment by larshp** [comment] 2019-10-14 06:03
@roman0701 try again, latest version, PR merged

**Closed** 2020-01-24 13:59 UTC
