### ISSUE TITLE
Short dump on ASSERT in ZCL_ABAPGIT_GUI_PAGE_STAGE=>STAGE_SELECTED

### ISSUE THREAD

**Issue by jwigert** [larshp/abapGit#3073] opened 2019-11-19 13:54 UTC
Hello,

In `ZCL_ABAPGIT_GUI_PAGE_STAGE=>STAGE_SELECTED`, the following `ASSERT` fails for some files:

```abap
      READ TABLE ms_files-status ASSIGNING <ls_status>
        WITH TABLE KEY
          path     = ls_file-path
          filename = ls_file-filename.
      ASSERT sy-subrc = 0.
```

The object types I've seen this happen for are:

- R3TR	IWMO	SAP Gateway Business Suite Enablement - Model
- R3TR	IWSV	SAP Gateway Business Suite Enablement - Service

The `READ` fails since whitespaces are handled differently.

Example:

```abap
ls_file-filename = 'zcrm_appointment_mdl 0001.iwmo.xml'.
```
Note that there is only 1 whitespace character between `zcrm_appointment_mdl` and `0001.iwmo.xml`.

```abap
MS_FILES-STATUS[6412]-FILENAME = 'zcrm_appointment_mdl            0001.iwmo.xml'.
```

Note that there are 12 whitespace characters between `zcrm_appointment_mdl` and `0001.iwmo.xml`.

Since the number of whitespaces differ, the `READ` fails, and the `ASSERT` causes a short dump.

It seems like the number of whitespaces is always 1 in `ls_file-filename`, but varies in `MS_FILES-STATUS[]-FILENAME`. It seems like the full length of `MS_FILES-STATUS[]-FILENAME` is 45 characters, and the number of whitespaces is adjusted to fill out the 45 characters.

I'd be happy to help creating a solution to this issue, but I'm not sure what the expected behavior is, and where the logic of whitespace handling needs to be adjusted. Please provide me with some guidance, and I'd be happy to create a PR.

Kind regards,
Johan

**Comment by larshp** [comment] 2019-11-21 05:49
`MS_FILES-STATUS[6412]-FILENAME` is the right value, `ls_file` comes from the postdata in the gui, it looks like encoding problems in the gui

**Comment by jwigert** [comment] 2019-11-22 14:46
Hi,
I started by looking into the serialization in ```ZCL_ABAPGIT_SERIALIZE->ON_END_OF_TASK```, just to be sure that there was no issue there. Here everything looks fine.

I continued by looking into the stage HTML page, and there the spaces are preserved:

```HTML
          <tr class="local">
            <td>
              <span class="state-block"><span class="none" title="Local: No changes">&nbsp;</span><span class="changed" title="Remote: Modified">M</span></span>
            </td>
            <td class="type">IWMO</td>
            <td class="name"><a href="sapevent:go_diff?KEY=000000000008&PATH=%2fsrc%2fzactivity%2fzactivity_or%2fzactivity_or_gateway%2f&FILENAME=z_or_activity_mdl%20%20%20%20%20%20%20%20%20%20%20%20%20%20%200001.iwmo.xml">/src/zactivity/zactivity_or/zactivity_or_gateway/z_or_activity_mdl&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0001.iwmo.xml</a></td>
            <td class="user">unknown</td>
            <td class="transport"></td>
            <td class="status">?</td>
            <td class="cmd"></td>
          </tr>
```

When I proceed to commit the staged files, the data in ```M_POSTDATA``` is wrong already when the ```SAPEVENT``` is raised in ```CL_GUI_HTML_VIEWER->DISPATCH```. Then the faulty data is just passed forward until it reaches ```ZCL_ABAPGIT_GUI_PAGE_STAGE->STAGE_SELECTED```.

Do you have any suggestion on how to proceed?

**Comment by FreHu** [comment] 2019-11-28 10:48
Hi @jwigert , did you make any progress on this? If this is a bug in sap, the right approach would be to make a small reproducible example which demonstrates spaces being lost and get it fixed. I can help you move this along internally.

**Comment by jwigert** [comment] 2019-11-28 12:21
Hi @FreHu , not really. What I've done is deleting the repo in my sandbox system, and then creating it again. In the newly created repo, the issue doesn't occur, even though the files are the same as before when I had the issue. I can't see any difference in the file names before and after the recreation of the repo though, so I'm not really any closer to understanding the issue. I'm not very keen on deleting and recreating the repo in the development system, where I also have the issue. If you have any ideas, I'd be happy to try them out.

**Comment by FreHu** [comment] 2019-11-28 13:14
I've also had this happen, both the dump and its disappearance. I assume this is one of those bugs which only occur when Neptune happens to be in a specific position. My investigations also pointed to the postdata getting messed up though.

**Comment by jwigert** [comment] 2019-11-28 14:03
Ok, I see. What is your opinion on the ASSERT statement? Do you think we could "relax" it a bit, and maybe issue a warning instead of creating a short dump?

**Comment by FreHu** [comment] 2019-11-28 14:23
I don't like asserts in general because of the dumping behavior, although in abapgit they are all over the place. A warning/error would definitely be better here.

In my own code I use a custom no_check exception which acts as an assertion and I only handle it at the top level.

**Comment by jwigert** [comment] 2019-11-28 14:59
Thanks, I'll do something similar locally in my dev environment.

**Comment by FreHu** [comment] 2019-11-28 15:14
Don't close this though, the problem still exists :)

**Comment by flaiker** [comment] 2020-01-03 16:37
Just had this happen to me after updating abapGit. Currently can't commit anything in repos with IW* objects, which will also kill my background mode job :/

`LS_FILE-FILENAME`:

<pre>#abc#abc_abc_mdl 0001.iwmo.xml</pre>

In `MS_FILES-STATUS` the object has this filename:

<pre>#abc#abc_abc_mdl                0001.iwmo.xml</pre>

I'll probably exclude these objects using CHANGE_TADIR for now.

**Comment by flaiker** [comment] 2020-01-03 16:49
Aaand now it suddenly works again o0

**Comment by FreHu** [comment] 2020-01-06 09:32
> Seems to be dependant on how many objects you stage?!

Theory: this is a leading/trailing blanks issue. If the spaces in the post data end up being at the start or the end of a line, they get removed.

**Comment by flaiker** [comment] 2020-01-06 09:45
I spend some time debugging it. Issue seems to be in `DP_GET_CLIENT_TABLE45A` which gets executed on the frontend. I was unable to create a minimal reproduceable example.

Another theory is that the action for each object is at fault, as one of them is the question mark character which gets replaced while the others are not. If that's the case we could just use a different character that does not get masked in any way to circumvent the issue.

**Comment by MDJoerg** [comment] 2020-01-06 17:16
Hi,
I have the same issue with "IATU" objects (abapgit version 1.92.0):
ms_files-obj_name = "ZWMRF         9910  SAPLLXSER"
ms_files-filename = "zwmrf         9910  sapllxser.iatu.html"

Inside method ZCL_ABAPGIT_GUI_PAGE_STAGE=>STAGE_SELECTED the content of <ls_item>-name = "/src/zwmrf/zwmrf   9910  sapllxser.iatu.html" splitted into
PATH = "/src/zwmrf/"
FILENAME = "zwmrf   9910  sapllxser.iatu.html"

Removing the assert statement seems to be no solution because of wrong content of <ls_item>. The spaces are lost before this method while building lt_fields?

The value in lv_string (lt_fields = zcl_abapgit_html_action_utils=>parse_fields( lv_string ).) contains the correct count of spaces.

**Comment by flaiker** [comment] 2020-01-09 20:58
Heh, now I have an example where the dump only happens if I press the "Changed by (me)" filter option in the stage screen. Looking at the GUI trace it seems to be already send with the wrong amount of spaces. If you undo the filter the dump still occurs. Seems like filtering somehow corrupts the spaces I guess.

Commit selected without filter by me:
<pre>
HTMLViewer: Size of Postdata after Transformation: 3716
HTMLViewer: Postdata after Transformation
HTMLViewer: /.abapgit.xml=A&/src/zcl_ztest_dpc.clas.abap=A&/src/zcl_ztest_dpc.clas.xml=A&/src/zcl_ztest_dpc_ext.clas.abap=A&/src/zcl_ztest_dpc_ext.clas.xml=A&/src/zcl_ztest_mpc.clas.abap=A&/src/zcl_ztest_mpc.clas.xml=A&/src/zcl_ztest_mpc_ext.clas.abap=A&/src/zcl_ztest_mpc_ext.clas.xml=A&/src/ztest_iw1.ddls.asddls=A&/src/ztest_iw1.ddls.xml=A&/src/ztest_elem_________________00.dtel.xml=A&/src/ztest_elem_________________001.dtel.xml=A&/src/ztest_elem_________________002.dtel.xml=A&/src/ztest_elem_________________003.dtel.xml=A&/src/ztest_elem_________________004.dtel.xml=A&/src/ztest_elem_________________005.dtel.xml=A&/src/ztest_elem_________________006.dtel.xml=A&/src/ztest_elem_________________007.dtel.xml=A&/src/ztest_elem_________________008.dtel.xml=A&/src/ztest_elem_________________009.dtel.xml=A&/src/ztest_elem_________________010.dtel.xml=A&/src/ztest_elem_________________011.dtel.xml=A&/src/ztest_elem_________________012.dtel.xml=A&/src/ztest_elem_________________101.dtel.xml=A&/src/ztest_elem_________________103.dtel.xml=A&/src/ztest_elem_________________104.dtel.xml=A&/src/ztest_elem_________________105.dtel.xml=A&/src/ztest_elem_________________106.dtel.xml=A&/src/ztest_elem_________________107.dtel.xml=A&/src/ztest_elem_________________108.dtel.xml=A&/src/ztest_elem_________________109.dtel.xml=A&/src/ztest_elem_________________110.dtel.xml=A&/src/ztest_elem_________________111.dtel.xml=A&/src/ztest_elem_________________112.dtel.xml=A&/src/ztest_elem_________________113.dtel.xml=A&/src/ztest_elem_________________114.dtel.xml=A&/src/ztest_elem_________________115.dtel.xml=A&/src/ztest_elem_________________116.dtel.xml=A&/src/ztest_elem_________________117.dtel.xml=A&/src/ztest_elem_________________118.dtel.xml=A&/src/ztest_elem_________________119.dtel.xml=A&/src/ztest_elem_________________120.dtel.xml=A&/src/ztest_elem_________________121.dtel.xml=A&/src/ztest_elem_________________122.dtel.xml=A&/src/ztest_elem_________________123.dtel.xml=A&/src/ztest_elem_________________124.dtel.xml=A&/src/ztest_elem_________________125.dtel.xml=A&/src/ztest_elem_________________126.dtel.xml=A&/src/ztest_elem_________________127.dtel.xml=A&/src/ztest_elem_________________128.dtel.xml=A&/src/ztest_elem_________________129.dtel.xml=A&/src/ztest_elem_________________130.dtel.xml=A&/src/ztest_elem_________________131.dtel.xml=A&/src/ztest_elem_________________132.dtel.xml=A&/src/ztest_elem_________________133.dtel.xml=A&/src/ztest_elem_________________134.dtel.xml=A&/src/ztest_elem_________________135.dtel.xml=A&/src/ztest_elem_________________136.dtel.xml=A&/src/ztest_elem_________________137.dtel.xml=A&/src/ztest_elem_________________138.dtel.xml=A&/src/ztest_elem_________________139.dtel.xml=A&/src/ztest_elem_________________140.dtel.xml=A&/src/ztest_elem_________________141.dtel.xml=A&/src/ztest_elem_________________142.dtel.xml=A&/src/ztest_elem_________________143.dtel.xml=A&/src/ztest_elem_________________144.dtel.xml=A&/src/ztest_elem_________________145.dtel.xml=A&/src/ztest_elem_________________146.dtel.xml=A&/src/ztest_elem_________________147.dtel.xml=A&/src/ztest_elem_________________148.dtel.xml=A&/src/ztest_elem_________________149.dtel.xml=A&/src/ztest_elem_________________150.dtel.xml=A&/src/ztest_elem_________________151.dtel.xml=A&/src/ztest_elem_________________152.dtel.xml=A&/src/ztest_elem_________________153.dtel.xml=A&/src/ztest_mdl                       0001.iwmo.xml=A&/src/ztest_mdl_0001_be.iwom.xml=A&/src/ztest_srv_0001.iwsg.xml=A&/src/ztest.iwpr.xml=A&/src/ztest_srv                          0001.iwsv.xml=A&/src/ztest_copy.prog.abap=A&/src/ztest_copy.prog.xml=A&/src/ztest_srv      ab038b227f774866dc7c68a94.sicf.xml=A&/src/package.devc.xml=A
HTMLViewer: Used time for postdata transformation: 78 ms.
</pre>

Commit selected with filter by me:
<pre>
HTMLViewer: Size of Postdata after Transformation: 3676
HTMLViewer: Postdata after Transformation
HTMLViewer: /.abapgit.xml=%3F&/src/zcl_ztest_dpc_ext.clas.abap=A&/src/zcl_ztest_dpc_ext.clas.xml=A&/src/zcl_ztest_dpc.clas.abap=A&/src/zcl_ztest_dpc.clas.xml=A&/src/zcl_ztest_mpc.clas.abap=A&/src/zcl_ztest_mpc.clas.xml=A&/src/zcl_ztest_mpc_ext.clas.abap=A&/src/zcl_ztest_mpc_ext.clas.xml=A&/src/ztest_iw1.ddls.asddls=A&/src/ztest_iw1.ddls.xml=A&/src/ztest_elem_________________00.dtel.xml=A&/src/ztest_elem_________________001.dtel.xml=A&/src/ztest_elem_________________002.dtel.xml=A&/src/ztest_elem_________________003.dtel.xml=A&/src/ztest_elem_________________004.dtel.xml=A&/src/ztest_elem_________________005.dtel.xml=A&/src/ztest_elem_________________006.dtel.xml=A&/src/ztest_elem_________________007.dtel.xml=A&/src/ztest_elem_________________008.dtel.xml=A&/src/ztest_elem_________________009.dtel.xml=A&/src/ztest_elem_________________010.dtel.xml=A&/src/ztest_elem_________________011.dtel.xml=A&/src/ztest_elem_________________012.dtel.xml=A&/src/ztest_elem_________________101.dtel.xml=A&/src/ztest_elem_________________103.dtel.xml=A&/src/ztest_elem_________________104.dtel.xml=A&/src/ztest_elem_________________105.dtel.xml=A&/src/ztest_elem_________________106.dtel.xml=A&/src/ztest_elem_________________107.dtel.xml=A&/src/ztest_elem_________________108.dtel.xml=A&/src/ztest_elem_________________109.dtel.xml=A&/src/ztest_elem_________________110.dtel.xml=A&/src/ztest_elem_________________111.dtel.xml=A&/src/ztest_elem_________________112.dtel.xml=A&/src/ztest_elem_________________113.dtel.xml=A&/src/ztest_elem_________________114.dtel.xml=A&/src/ztest_elem_________________115.dtel.xml=A&/src/ztest_elem_________________116.dtel.xml=A&/src/ztest_elem_________________117.dtel.xml=A&/src/ztest_elem_________________118.dtel.xml=A&/src/ztest_elem_________________119.dtel.xml=A&/src/ztest_elem_________________120.dtel.xml=A&/src/ztest_elem_________________121.dtel.xml=A&/src/ztest_elem_________________122.dtel.xml=A&/src/ztest_elem_________________123.dtel.xml=A&/src/ztest_elem_________________124.dtel.xml=A&/src/ztest_elem_________________125.dtel.xml=A&/src/ztest_elem_________________126.dtel.xml=A&/src/ztest_elem_________________127.dtel.xml=A&/src/ztest_elem_________________128.dtel.xml=A&/src/ztest_elem_________________129.dtel.xml=A&/src/ztest_elem_________________130.dtel.xml=A&/src/ztest_elem_________________131.dtel.xml=A&/src/ztest_elem_________________132.dtel.xml=A&/src/ztest_elem_________________133.dtel.xml=A&/src/ztest_elem_________________134.dtel.xml=A&/src/ztest_elem_________________135.dtel.xml=A&/src/ztest_elem_________________136.dtel.xml=A&/src/ztest_elem_________________137.dtel.xml=A&/src/ztest_elem_________________138.dtel.xml=A&/src/ztest_elem_________________139.dtel.xml=A&/src/ztest_elem_________________140.dtel.xml=A&/src/ztest_elem_________________141.dtel.xml=A&/src/ztest_elem_________________142.dtel.xml=A&/src/ztest_elem_________________143.dtel.xml=A&/src/ztest_elem_________________144.dtel.xml=A&/src/ztest_elem_________________145.dtel.xml=A&/src/ztest_elem_________________146.dtel.xml=A&/src/ztest_elem_________________147.dtel.xml=A&/src/ztest_elem_________________148.dtel.xml=A&/src/ztest_elem_________________149.dtel.xml=A&/src/ztest_elem_________________150.dtel.xml=A&/src/ztest_elem_________________151.dtel.xml=A&/src/ztest_elem_________________152.dtel.xml=A&/src/ztest_elem_________________153.dtel.xml=A&/src/ztest_mdl 0001.iwmo.xml=%3F&/src/ztest_mdl_0001_be.iwom.xml=%3F&/src/ztest_srv_0001.iwsg.xml=%3F&/src/ztest_srv 0001.iwsv.xml=%3F&/src/ztest_copy.prog.abap=A&/src/ztest_copy.prog.xml=A&/src/ztest.iwpr.xml=%3F&/src/ztest_srv ab038b227f774866dc7c68a94.sicf.xml=A&/src/package.devc.xml=A
HTMLViewer: Used time for postdata transformation: 16 ms.
</pre>

After some debugging I noticed the apply function for the filter seems to incorrectly handle spaces:
![image](https://user-images.githubusercontent.com/5270359/72102992-8ae20c80-3328-11ea-9edc-2ebf9b3a1555.png)

https://github.com/larshp/abapGit/blob/1a896613b4394258f4785bf5fd42800d0b01028b/src/ui/zabapgit_js_common.w3mi.data.js#L462-L478

I applied this patch to get the stage screen to work after applying any kind of filter:

```diff
   // Apply filter to cells, mark filtered text
   for (var i = targets.length - 1; i >= 0; i--) {
     var target = targets[i];
     target.newHtml = (filter)
       ? target.plainText.replace(filter, "<mark>"+filter+"</mark>")
       : target.plainText;
+    target.newHtml = target.newHtml.replace(/ /g, '\u00a0')
     target.isChanged = target.newHtml !== target.curHtml;
     isVisible        = isVisible || !filter || target.newHtml !== target.plainText;
   }

   // Update DOM
   row.style.display = isVisible ? "" : "none";
   for (var j = targets.length - 1; j >= 0; j--) {
     if (targets[j].isChanged) targets[j].elem.innerHTML = targets[j].newHtml;
   }
   return isVisible ? 1 : 0;
 };
```

I don't think the spaces should be there though at all? At least they are neither in the repo view nor included in the created file by commit.

**Closed** 2020-07-16 13:51 UTC

**Comment by jwigert** [comment] 2020-12-15 13:22
I managed to get the error after having added a file manually in the repo. I added a markdown file with some documentation directly to the repo and accidentally named it with upper case letters, e.g. `ZD_AUTHORIZATION.md`. When I tried to ignore the file in the stage step in abapGit, I got the same error message as discussed above. To resolve the issue I just had to rename the file to lower case letters, e.g. `zd_authorization.md`. Just thought I'd add this comment in case someone else does the same mistake.

**Comment by mbtools** [comment] 2020-12-19 21:19
@jwigert after reading your blog, it looks like you're using MD files regularly. Probably best to put a pattern into abapGit.xml to ignore all MD files: `*.md` should do.

**Comment by christianguenter2** [comment] 2021-03-25 13:52
We have this problem too and made the following observation. Spaces seem to be encoded differently. I try to investigate further.
![image](https://user-images.githubusercontent.com/17437789/112483503-60d40900-8d79-11eb-9f2b-4a647c5555d7.png)
![image](https://user-images.githubusercontent.com/17437789/112483295-2ec2a700-8d79-11eb-8356-9f295b65e0ff.png)

**Comment by christianguenter2** [comment] 2021-03-25 13:56
Seems to be related to `unescape_url`.
![image](https://user-images.githubusercontent.com/17437789/112484406-3171cc00-8d7a-11eb-8ede-c3cc4ffe48e2.png)

**Comment by mbtools** [comment] 2021-03-25 15:45
Spaces in filenames should be encoded to %20. Can you check if adding this here helps?

```abap
      REPLACE ALL OCCURRENCES OF ` ` IN lv_obj_name WITH '%20'.
```

https://github.com/abapGit/abapGit/blob/main/src/objects/core/zcl_abapgit_objects_files.clas.abap#L240

**Comment by christianguenter2** [comment] 2021-03-27 08:30
@mbtools 
No, that didn't help. Figured out that &nbsp; (non-breaking space) is the problem. `unescape_url` can't handle it and replaces it with `#`. Replacing &nbsp; in zcl_abapgit_html_action_utils with space does the job. Preparing a PR...
