### ISSUE TITLE
DOMA: fixed value append, 'value doesn't exist'

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1048] opened 2017-11-09 06:32 UTC
see below

**Comment by gajulahari69** [comment] 2017-11-11 09:06
We are facing the same problem in extension of fixed values in Domain - DEVICEID using 'Fixed Value Append'. 
Initially,  we added list of values to domain using 'Fixed Value Append' and it was working fine. Later, another value was added in the middle of the list with respective to alphabetic order. when we are selecting the newly selected value from the list at transaction level, encountering with an error message 'value doesn't exist'.

How can I clear and re-build the index or VALPOS?

**Comment by larshp** [comment] 2017-11-11 09:19
the error "value doesnt exist" does this appear after pulling the git repository? 

I have not tested Fixed Value Appends in abapGit, it looks like they are saved as DOMA objects, but we probably need some more information in the XML to support fixed value appends

**Comment by larshp** [comment] 2017-11-11 10:11
did some testing in https://github.com/larshp/DOMA I am unable to reproduce the issue, can you try reproducing the issue in a public repository?

**Comment by larshp** [comment] 2017-11-18 08:14
@gajulahari69 can you help reproducing the issue?

**Comment by EduardoCopat** [comment] 2018-08-23 17:35
I also could not reproduce the issue (`v1.74.1`, abap 7.5). See commits https://github.com/EduardoCopat/abap-sandbox/commit/5b219f257aaca5eda478637afb6aceec41280be5 and https://github.com/EduardoCopat/abap-sandbox/commit/7e3928341f5a8705e1b331dccd30318dbc954d57. VALPOS is being recalculated.

 I will close the issue. 

@gajulahari69: If you are still facing this issue, could you provide a public repository with an example, reopening this issue?

**Closed by EduardoCopat** 2018-08-23 17:35 UTC
Labels: bug
