### ISSUE TITLE
Error "unexpected folder structure" during zip import

### ISSUE THREAD

**Issue by testitorleaveit** [larshp/abapGit#1411] opened 2018-05-23 14:05 UTC
When I try to import the following zip into a offline project, I get the error mentioned in the title.

Here is the zip: https://open.sap.com/files/f94c899c-62ae-4c79-81ff-c05d3b44c390

Reproduction:
+Offline
package $WTC1
create package $WTC1
Import
Select the zip
-> error

Happened on NW 7.30 and NW 7.51. abapGit version 1.67  2018-05-22T19:07:46.531Z

The same zip worked for sure with 1.60 or 1.61.

**Comment by christianguenter2** [comment] 2018-05-23 14:26
I think this is related to [1383](https://github.com/larshp/abapGit/pull/1383). Can you either put all files and folders except .abapgit.xml into a folder named src or change the starting folder to /.
![image](https://user-images.githubusercontent.com/17437789/40430713-057ad110-5ea6-11e8-86d0-6da150404e23.png)

**Comment by christianguenter2** [comment] 2018-05-23 14:30
Can't reproduce it on my 7.51.

**Comment by christianguenter2** [comment] 2018-05-23 14:33
Can't reproduce it on my 7.51 with latest abapGit.

**Comment by testitorleaveit** [comment] 2018-05-23 14:48
It still reproduces for me, a fresh 7.51 in a virtual box with the latest abapGit.
When I change the starting folder from the default /src to / then the import works. So the workaround does work.

**Comment by larshp** [comment] 2018-05-23 17:02
the .abapgit.xml should be set via ZCL_ABAPGIT_REPO->FIND_REMOTE_DOT_ABAPGIT but I guess for some reason this does not work for ZIP files.

import zip code below, looks like FIND_REMOTE_DOT_ABAPGIT is called somewhere down in gui_deserialize. I currently dont have access to any test sytems, back in the office sometime during the weekend.
```abap
  METHOD import.

    DATA: lo_repo TYPE REF TO zcl_abapgit_repo_offline.


    lo_repo ?= zcl_abapgit_repo_srv=>get_instance( )->get( iv_key ).
    lo_repo->set_files_remote( unzip_file( file_upload( ) ) ).

    zcl_abapgit_services_repo=>gui_deserialize( lo_repo ).

  ENDMETHOD.
```

**Comment by larshp** [comment] 2018-05-27 15:19
I also cannot reproduce the issue, @testitorleaveit can you try setting a breakpoint in below code, and paste the values for `IV_PATH` and the `io_dot->get_starting_folder( )` ? Are you on windows using normal SAP GUI?

![image](https://user-images.githubusercontent.com/5888506/40587607-cf8832bc-61d1-11e8-88c4-1e92fb16b577.png)

**Comment by larshp** [comment] 2018-06-04 07:08
okay, this might be worth investigating, some of the zip stuff might not work as expected on Java/macOS

**Comment by larshp** [comment] 2018-07-28 10:16
there is an issue somewhere, but we are not able to reproduce it, hence I will close the issue

**Closed by larshp** 2018-07-28 10:16 UTC
Labels: bug
