### ISSUE TITLE
HTTP 500 error when doing a PULL in Eclipse

### ISSUE THREAD

**Issue by traimo** [larshp/abapGit#2632] opened 2019-04-15 17:55 UTC
Hello,

I'm trying to PULL my ABAP code that I saved into a Git Repo into my ABAP Cloud system using Eclipse.  I'm getting the following error (see screenshot).  When I check the Feed Reader in Eclipse, I see this error, DYNPRO_SEND_IN_BACKGROUND (see 2nd screenshot).  I submitted a ticket to SAP and they told me to update to the latest version of ABAPGit(1.86.2) and the ADT tools in Eclipse.  After doing that, I still get the same error.  SAP then told me to post my issue here.  Have you seen this error before?

![image](https://user-images.githubusercontent.com/22568869/56154022-69581e00-5f6c-11e9-8bb8-9854227b36e9.png)

![image](https://user-images.githubusercontent.com/22568869/56154136-b2a86d80-5f6c-11e9-8305-7a3ccde5b331.png)

Thank you

**Comment by traimo** [comment] 2019-04-15 19:07
Here is the entire dump file:

[ABAPGit_Dump.txt](https://github.com/larshp/abapGit/files/3081712/ABAPGit_Dump.txt)

**Comment by mfsap** [comment] 2019-04-16 07:20
This happens because zabapgit was originally designed to run with SAPGUI. Some internal function calls uses "NO_DIALOG = SPACE", but ADT plugin requires "NO_DIALOG = 'X'". I'll check in detail and prepare a fix for this issue...

**Comment by traimo** [comment] 2019-04-17 02:28
Hello,

I tried updating the Z ABAPGit objects on my on-prem abap system (source system) but I still get the same error in Eclipse.  I'm pretty sure the reason is because this fix needs to be rolled out to my target system which is on SAP Cloud Platform ABAP Environment.  The class name in the call stack is CL_ABAPGIT_OBJECT_MSAG.  How can we apply these changes to an ABAP Cloud environment?  Will these changes be available in the 1905 release scheduled in May.  Let me know.

Thank you,

**Comment by larshp** [comment] 2019-04-17 05:05
I dont know about the 1905 release

But as mentioned by Martin, "It usually happens if the current user has no open task in the selected transport request and the backend system needs confirmation that a new task is created for the user.". Are you the owner of the transport request? If not try adding a task for your user

**Comment by mfsap** [comment] 2019-04-17 08:31
I was not aware of 1902 release. I compared 1905 and 1902 and saw that we did not deliver #2392 in 1902. So in 1902 e.g. the SUPPRESS_DIALOG = 'X' is missing for object type MSAG. A deeper analysis of the short dump indicates that "the package /SEPCAR/CARRIER cannot be extended" (PAK134). I'm not 100% sure, but I guess this is related to #2378 (which is also fixed with #2392). I can't remember why we did not correct this with a hotfix in 1902, but the problem should not occur after the upgrade to 1905.
This problem is not related to my statement "current user has no open task in the selected transport request" - this was fine in the system. The error only belongs to missing #2392. Sorry!

**Comment by larshp** [comment] 2019-04-17 10:11
see `CL_PAK_OBJECT_TYPES=>CHECK_OBJECT_TYPE`

steps to reproduce:
1: clone https://github.com/larshp/package_add into a transported package(see logic in method CHECK_OBJECT_TYPE)
2: switch to branch "new"
3: pull
4: error

![image](https://user-images.githubusercontent.com/5888506/56280092-cc32ec00-6109-11e9-8f83-096b9b20ed38.png)

workaround: remove flag "Adding further objects not possible" for the package in the source system

abapGit change suggested: clear field RESTRICTED in serializer, https://github.com/larshp/package_add/blob/master/src/package.devc.xml#L7

**Comment by mfsap** [comment] 2019-04-18 07:17
In the destination system, the restricted flag is not set for the package. I checked TDEVC table.
@traimo: Could you please check/verify if the restricted flag is set in the source system (or in the repository)?

**Comment by traimo** [comment] 2019-04-18 14:01
It is not set.  Here are some screen shots.

![image](https://user-images.githubusercontent.com/22568869/56366326-baa02180-61a7-11e9-856d-772412935c0e.png)

![image](https://user-images.githubusercontent.com/22568869/56366334-bf64d580-61a7-11e9-86a7-29c5dae6fb5c.png)

![image](https://user-images.githubusercontent.com/22568869/56366347-c4c22000-61a7-11e9-88d4-69bbf588c9b2.png)

![image](https://user-images.githubusercontent.com/22568869/56366352-c8ee3d80-61a7-11e9-96c1-7575c2424dbf.png)

Thank you,

**Comment by traimo** [comment] 2019-04-23 15:07
SAP support has confirmed that the issue is on their side and it will be fixed with the 1905 release.

**Comment by larshp** [comment] 2019-08-08 05:11
I guess this issue can be closed?

**Comment by traimo** [comment] 2019-08-08 05:19
Yes.  Please close.



Sent from my Sprint Samsung Galaxy S9+.


-------- Original message --------

**Closed** 2019-08-08 05:21 UTC
