### ISSUE TITLE
Function group... IN UPDATE TASK flag not updated

### ISSUE THREAD

**Issue by nununo** [larshp/abapGit#352] opened 2016-09-20 15:08 UTC
Hi,

It looks like the IN UPDATE TASK flag is not being updated:

![image](https://cloud.githubusercontent.com/assets/532049/18676118/705bc4f2-7f4c-11e6-86f2-44e87857bb0b.png)

Thanks,
Nuno

**Comment by nununo** [comment] 2016-09-20 15:10
I'm not sure what it is nor if it is related but this flag in the top is also not being updated:

![image](https://cloud.githubusercontent.com/assets/532049/18676208/ba5b18aa-7f4c-11e6-9033-f4ae9c6fa927.png)

**Comment by larshp** [comment] 2016-09-21 16:57
UPDATE_TASK: I have reproduced the issue, clone https://github.com/larshp/CLAS and it shows a diff

VARCL: I guess this is a separate issue, will look into the UPDATE_TASK first

**Comment by larshp** [comment] 2016-09-21 17:27
VARCL: in the standard code it sets VARCL to 'X'. Any chance that the code in the source system is quite old?

![image](https://cloud.githubusercontent.com/assets/5888506/18721513/274ec814-8031-11e6-98b9-8dc7a3d4f042.png)

**Comment by nununo** [comment] 2016-09-27 12:59
> VARCL: in the standard code it sets VARCL to 'X'. Any chance that the code in the source system is quite old?

No... all this is recently created code.

**Comment by nununo** [comment] 2016-09-27 13:12
Actually I just created a new function group moments ago and the same happpened:

![image](https://cloud.githubusercontent.com/assets/532049/18875149/6e94414c-84bc-11e6-9d79-b0fe83bc31f3.png)

**Comment by larshp** [comment] 2016-09-27 14:14
yea, I also saw the problem in some of my code a few days ago. Looks like VARCL is always blank for the TOP includes in function groups

**Comment by nununo** [comment] 2016-09-27 15:12
Is it simple to solve? I now have a diff for each function group I create :)

**Comment by larshp** [comment] 2016-09-27 15:27
temporary workaround is to update the field in PROGDIR(REPOSRC?) manually

I'm not sure how to fix it in abapGit, perhaps skip calling the UPDATE_PROGDIR function module and add the functionality in custom code

**Comment by larshp** [comment] 2016-11-17 10:01
closing this issue, topic is misleading as the UPDATE TASK has been fixed, 

VARCL issue moved to https://github.com/larshp/abapGit/issues/435

**Closed by larshp** 2016-11-17 10:01 UTC
