### ISSUE TITLE
HTTP error 407 occured: SSL handshake with github.com:443 failed: SSSLERR_SSL_READ (-58) SAPCRYPTO:SSL_read() failed SapSSLSessionStartNB()==SSSLERR_SSL_READ SSL:SSL_read() failed (536875120/0x200

### ISSUE THREAD

**Issue by Suncatcher** [larshp/abapGit#2991] opened 2019-10-22 01:47 UTC
This happens when I try to add online repo. I imported the certificate into STRUST. What to try else?

**Comment by g-back** [comment] 2019-10-22 05:09
Have you tried running report ZABAPGIT_TEST_SSL?
Had the same issue last week, had to import another certificate for api.github.com.

**Comment by Suncatcher** [comment] 2019-10-22 21:25
This is exactly what ZABAPGIT_TEST_SSL shows

![image](https://user-images.githubusercontent.com/6388034/67334891-e0a8d480-f4f0-11e9-9470-986f150e1c95.png)

Does it mean I imported the wrong certificate?

**Comment by Suncatcher** [comment] 2019-10-22 21:33
Also according to manual guide I imported this cert which supposed to be used on Github

![image](https://user-images.githubusercontent.com/6388034/67335578-f2d74280-f4f1-11e9-8cd9-100d478739dd.png)

but this had no result.

**Comment by Suncatcher** [comment] 2019-10-22 21:34
>  had to import another certificate for api.github.com

could you please elaborate more how did you do this?

**Comment by larshp** [comment] 2019-10-23 02:50
see the documentation https://docs.abapgit.org/guide-ssl-setup.html, last section

**Comment by Suncatcher** [comment] 2019-10-24 01:00
Ok, I added all three certificates [like here](https://www.dropbox.com/s/oder81vnwhfw7sz/strust2.PNG?dl=0) but it throws the same error. What am I missing?

**Comment by mariusraht2** [comment] 2019-11-05 09:51
The message suggests that SAP doesn't use TLS 1.2 for the HTTPS connection handling. The parameters you mentioned should fix that. You have to maintain them in RZ10 > Profile "Default" and current version > Extended Maintenance.

**Comment by mariusraht2** [comment] 2019-11-18 22:01
@Suncatcher Did you solve this issue?

**Comment by Suncatcher** [comment] 2019-11-18 22:49
Not yet. Don't close the issue

**Comment by beyondnk** [comment] 2019-11-29 07:26
Github doesn't support TLS 1.0.
(https://github.blog/2018-02-23-weak-cryptographic-standards-removed/)

Check SAP TLS version.

Go to T-Code: STRUST 
Menu->Environment -> Display SSF Version 

If CommonCryptoLib version is lower than 8.5.x, implement note "1848999 - Central Note for CommonCryptoLib 8.pdf".
(We are 8.5.23, 8.5.28.) 

Profile parameters are same.

Ask BC for help~(I am not an Admin;)

I hope it will help you.

**Comment by himanshush13** [comment] 2019-12-06 11:04
Getting the same issue, also imported 3 certificates as directed above, but still its not enough. Can the basis team help or it is not the issue of certificates but something else. @Suncatcher @larshp

**Comment by himanshush13** [comment] 2019-12-06 11:06
Also @mariusraht2  you are talking about  4 certificates so please can you mention the links or names of all of them, because now its been a while about this issue as it is taking too long

**Comment by mariusraht2** [comment] 2019-12-06 11:11
> 
> 
> Also @mariusraht2 you are talking about 4 certificates so please can you mention the links or names of all of them, because now its been a while about this issue as it is taking too long

I did in my previous post:
**github.com** and **api.github.com**
![grafik](https://user-images.githubusercontent.com/45243391/70318894-62df2500-1821-11ea-8034-d8cf2523b970.png)
![grafik](https://user-images.githubusercontent.com/45243391/70318981-7a1e1280-1821-11ea-832f-34ee939f60b8.png)

**Comment by larshp** [comment] 2020-03-29 11:46
closing, this is most likely due to system setup, not a bug in abapGit

**Closed by larshp** 2020-03-29 11:46 UTC
Labels: question
