### ISSUE TITLE
Assert failed in ZCL_ABAPGIT_ZLIB->Decompress

### ISSUE THREAD

**Issue by matt1as** [larshp/abapGit#2483] opened 2019-03-05 08:42 UTC
When trying to open my repository there's an assertion failed in zcl_abapgit_zlib. Unfortunatly my debug-voodo is not enough to figure out what's happening.

The failed assertion is 

```
DO.
      lv_bfinal = go_stream->take_bits( 1 ).

      lv_btype = go_stream->take_bits( 2 ).
      CASE lv_btype.
        WHEN '01'.
          fixed( ).
        WHEN '10'.
          dynamic( ).
        WHEN OTHERS.
          ASSERT 1 = 0.
      ENDCASE.
```

And lv_btype for me is 00.

Not sure what I should do, or if I need to scrap my local repo and create a new.

**Comment by larshp** [comment] 2019-03-05 08:47
`00` is "non-compressed blocks", see https://www.ietf.org/rfc/rfc1951.txt section 3.2.4, guess it is an easy case to implement

**Comment by matt1as** [comment] 2019-03-05 09:59
I will give it a shot, but it's going to be interesting:-) Had a look at dynamic and it's not very commented, What is expected to be returned from the method?

**Comment by larshp** [comment] 2019-03-05 10:09
I dont remember, but the code follows RFC1951 linked above

**Comment by larshp** [comment] 2019-03-10 09:27
@matt1as what software/host do you use for the git code? The zlib libs used between providers vary a bit, so sometimes things like this comes up. Need to know the provider in order to try reproducing the issue

**Comment by matt1as** [comment] 2019-03-10 09:35
Azure Devops ( https://azure.microsoft.com/en-us/services/devops/ )

I tried implementing the non-compressed-case but right now I'm getting a checksum error, I guess my approach was very very naive. I don't have the code available from home, but I will try to create a PR on Monday to show what I've done.

**Comment by larshp** [comment] 2019-03-10 09:51
suggest first trying to reproduce in a public repo, https://docs.microsoft.com/en-us/azure/devops/organizations/public/about-public-projects?view=azure-devops

just upload different code until it breaks, or try using the git part to clone different projects until we hit the example

**Comment by matt1as** [comment] 2019-03-11 12:11
Not sure I could do that, we have something like 70 000 files in this repo (I know it's way too big, but that's what happens when you don't use packages...) 

I did check what was added the last commit, assuming that that was breaking stuff, and there're are JS files that looks strange. They are fiori files that were deployed from WebIDE to CRM, but they don't have any file ending, maybe this causes Devops not to compress? If I clone to my local computer they are called something like (notice the . in the end)

zgateway_foretag_kontakter/zcrm_mycontacts.wapa.ui545aec4a4016d8fe9df7666a9ef4771b1187b8829.

**Comment by matt1as** [comment] 2019-03-11 12:15
These files where commited before #2426  was applied, maybe I could remove them and re-add the files again.

**Comment by matt1as** [comment] 2019-03-11 12:21
Closing this as it was related to #2425 . Azure Devops was confused by the . file-ending

**Comment by larshp** [comment] 2019-03-12 05:28
its still a bug, but anyhow

**Comment by larshp** [comment] 2019-03-13 09:03
tried adding a file "foobar." to https://dev.azure.com/larshvam/public however the normal git client or the web ui does not allow it

**Comment by larshp** [comment] 2019-03-16 11:30
will close this for now, we cannot reproduce

**Comment by sandraros** [comment] 2019-03-28 13:24
I've just got the bug today (Azure DevOps too). I prefer to debug the data & decode algorithm rather than trying to reproduce elsewhere.

**Comment by sandraros** [comment] 2019-03-28 14:38
I have implemented successfully the algorithm (I can now push and pull). I could just see that the concerned objects were the "tree" objects (100644...), I didn't analyze further. @larshp as you know I'm new to Git so I have one pull request #2578 in my main branch, could you merge it ASAP so that I can recreate my fork correctly and create a branch for the "non-compressed" correction ? (or is there any other simple possibility?)

**Comment by larshp** [comment] 2019-03-28 15:36
I dont want to merge it until I have looked through the changes.

It is possible to do git magic to move the commits to new branches, however I'm no expert in this. Another (easy?) alternative is to close the PR, download the ABAP changes to ZIP, recreate the fork, and do branching and PRs from there.

**Comment by sandraros** [comment] 2019-03-28 15:42
I am okay to close the PR and redo everything now the way you said. Do I close it now myself ?

**Comment by larshp** [comment] 2019-03-28 16:32
yea

**Comment by larshp** [comment] 2019-03-31 10:34
PR merged, closing

**Closed by larshp** 2019-03-31 10:34 UTC
Labels: bug
