### ISSUE TITLE
Having issues in abapgit - last updated 5th March 2018

### ISSUE THREAD

**Issue by A141117** [larshp/abapGit#1475] opened 2018-06-08 01:23 UTC
Hi,
I'm having issues in ZABAPGIT transaction, refer attached screen-shot in jpg file. This has been last updated on 5th march 2018. If I try to update it by copying the abapcode in SE38  then executing program is giving dump as attached in word doc.
How to resolve this or upgarde this?
[abapgit-error.docx](https://github.com/larshp/abapGit/files/2082582/abapgit-error.docx)
![abapgit-issue](https://user-images.githubusercontent.com/36180668/41134170-5cc04b34-6b0e-11e8-90ef-3933b6a80bba.JPG)

**Comment by larshp** [comment] 2018-06-08 04:37
workaround is to delete all objects in the $ABAPGIT package and install again

I'm not sure what is wrong, it is difficult to debug with such a large repository as abapGit

**Comment by A141117** [comment] 2018-06-08 04:51
I tried to do so but it does not allow me to delete. I tried to follow the uninstallation instructions and it did not allowed me to delete the enqueue object. So any suggestions on that?

**Comment by larshp** [comment] 2018-06-08 05:11
try deleting all the classes in the $ABAPGIT package. 

I dont think this error is caused by the enqueue object, which is located in $TMP

**Comment by A141117** [comment] 2018-06-08 05:48
I tried to uninstall the abapgit and repo class and deleted enquee and table. But stuck at the very last stage of uninstallation that is : 
"Delete mime objects ZABAPGIT_CSS_COMMON + ZABAPGIT_JS_COMMON in transaction SMW0".
I could not see any object with these names in this tcode SMW0. Suggest please.

**Comment by larshp** [comment] 2018-06-08 05:54
okay, I dont think the SMW0 objects are causing any problems. 

Go ahead and try installing the code by copy-pasting into SE38 again

**Comment by A141117** [comment] 2018-06-08 06:51
tried to install agaian and nw when i try to click on install abaGit repo then facing connection issues: “HTTP error 411 occurred: Connect to github.com.443 failed: NIECONN_REFUSED(-10)". Although the connection was working fine before uninstalling today. Any idea?

**Comment by christianguenter2** [comment] 2018-06-08 06:57
seems to be a temporary issue with gitHub. I have also connection problems currently.

**Comment by christianguenter2** [comment] 2018-06-08 07:02
It must be due to the microsoft aquisition ;-)

**Comment by christianguenter2** [comment] 2018-06-08 07:12
I get this one
![image](https://user-images.githubusercontent.com/17437789/41144118-10f7c68a-6afc-11e8-90e8-25c382c7276d.png)

**Comment by christianguenter2** [comment] 2018-06-08 07:31
It's working again for me

**Comment by A141117** [comment] 2018-06-12 03:42
I'm able to connect to github now and zabapgit transaction is working. However, I can see the below error messages on the zabapgit tcode when I select abapgit repository.

![image](https://user-images.githubusercontent.com/36180668/41269042-5d4a2288-6e46-11e8-81ef-67615c15af1d.png)

**Comment by larshp** [comment] 2018-06-12 04:59
See https://github.com/larshp/abapGit/issues/1483

Workaround is to move the objects to the right package manually

**Comment by A141117** [comment] 2018-06-12 05:07
these error are starnge. FOr example the CLAS ZCL_ABAPGIT_SERVICES_ABAPGIT is already in pacakge $ABAPGIT and still giving error.

**Comment by A141117** [comment] 2018-06-12 05:31
Is there any functionality change where multiple users cannot access same repository at same time. I mean parallel access to a repository will not work?

**Comment by A141117** [comment] 2018-06-12 05:41
@larshp - those warnings are removed when I changed the package manually. Thanks for all help. This thread can be closed now.

**Comment by larshp** [comment] 2018-06-12 05:53
cool, closing

**Closed by larshp** 2018-06-12 05:53 UTC
Labels: bug
