### ISSUE TITLE
Error when pulling changes

### ISSUE THREAD

**Issue by treisinger** [larshp/abapGit#2341] opened 2019-01-28 07:33 UTC
I receive an error when pulling objects from abapGitServer.

![image](https://user-images.githubusercontent.com/9279781/51820774-25dc0500-22d7-11e9-87bd-84bbf829f8d2.png)

When I click on the error message, it just show the message again. So, no details available.

**Comment by larshp** [comment] 2019-01-28 08:53
Try setting a breakpoint, https://github.com/larshp/abapGit/search?q=Prog%2C+error+updating&unscoped_q=Prog%2C+error+updating

**Comment by treisinger** [comment] 2019-01-28 10:13
![image](https://user-images.githubusercontent.com/9279781/51829326-9b52d000-22ed-11e9-8713-f246c9991907.png)

It is a generated view from table maintenance generator. Strange, so far I had never problems with generated views?!?

Is there an option to pull only a specific object or to exclude an object from pulling?

**Comment by larshp** [comment] 2019-01-28 10:49
duplicate of https://github.com/larshp/abapGit/issues/2235

**Comment by larshp** [comment] 2019-02-16 08:57
closing, duplicate of #2235

**Closed by larshp** 2019-02-16 08:57 UTC
Labels: bug
