### ISSUE TITLE
Object ZODA should be removed, but has NO deletion flag in transport

### ISSUE THREAD

**Issue by jwigert** [larshp/abapGit#2772] opened 2019-07-04 12:26 UTC
I've deleted an Authorization object class (R3TR - SUSC) named ZODA. When I try to transport to branch based on my transport request, I receive the error mesage: 
"Object ZODA should be removed, but has NO deletion flag in transport"

The error is thrown here: ZCL_ABAPGIT_TRANSPORT_OBJECTS->TO_STAGE

The two relevant structures have the following content:

LS_TRANSPORT_OBJECT:
PGMID	                                   	R3TR
OBJECT	                                   	SUSC
OBJ_NAME	                                   	ZODA
DEVCLASS	                                   	ZAUTHORIZATION
KORRNUM	                                   
DELFLAG	                                   
PATH	                               

LS_OBJECT_STATUS:
OBJ_TYPE	                                   	SUSC
OBJ_NAME	                                   	ZODA
INACTIVE	                                   
PATH	                                   	/src/zauthorization/
FILENAME	                                   	zoda.susc.xml
PACKAGE	                                   
MATCH	                                   
LSTATE	                                   	D
RSTATE	                                   

So the issue is that LS_TRANSPORT_OBJECT-DELFLAG is initial.

I'd be happy to try and create a PR for the issue, but I would need some guidance as to what to change.

**Comment by larshp** [comment] 2019-07-06 08:19
Hi,
I've created and deleted an authorization object class via transaction SU21, and TADIR-DELFLAG is not set, ie. from my point of view this error is caused by a bug in SAP standard.

If you have time suggest raising an incident with SAP.

In abapGit suggest skipping the error for SUSC objects.

**Comment by larshp** [comment] 2019-07-22 05:50
merged, closing issue

**Closed by larshp** 2019-07-22 05:50 UTC
