### ISSUE TITLE
ASSERTION_FAILED Dump while updating abap2xlsx

### ISSUE THREAD

**Issue by nomssi** [larshp/abapGit#1176] opened 2018-01-30 05:25 UTC
I have tried to update my abap2xlsx version and I failed. Using the latest abapgit, I get an ASSERTION_FAILED dump in method UPDATE_REPORT of class LCL_OO_CLASS_NEW. 
Variable _iv_program_ has value ZCL_EXCEL_WORKSHEET===========CCAU

![abapgit_error](https://user-images.githubusercontent.com/18452507/35549472-0c175a80-0586-11e8-9171-eae4dd4720bb.png)

Can anyone reproduce this?

**Comment by larshp** [comment] 2018-01-30 06:33
thanks, can you check if the include exists in your system, perhaps it is inactive?

**Comment by larshp** [comment] 2018-01-30 06:38
I think the issue is due to https://github.com/ivanfemia/abap2xlsx/blob/master/src/zcl_excel_worksheet.clas.xml not having `<WITH_UNIT_TESTS>X</WITH_UNIT_TESTS>`

try commenting the ASSERT, then I guess it would work, this is a quick workaround

as a fix, then the abap2xlsx XML file might need to be updated

**Comment by christianguenter2** [comment] 2018-01-30 10:15
commenting out leads to the next dump.
![image](https://user-images.githubusercontent.com/17437789/35560833-d7c10cee-05ae-11e8-9653-91a7bf8e7ffe.png)˙

Adding <WITH_UNIT_TESTS>X</WITH_UNIT_TESTS> fixes the issue. I did a PR.

**Comment by larshp** [comment] 2018-01-30 10:59
cool, perhaps we should add code so it shows an error for this case

**Comment by larshp** [comment] 2018-02-11 09:54
I think we can close this

**Closed by larshp** 2018-02-11 09:54 UTC
Labels: bug

**Comment by MLDOliveira** [comment] 2018-02-19 11:46
@larshp @christianguenter2 Wich line of the file zcl_excel_worksheet.clas.xml should I put this text?

**Comment by larshp** [comment] 2018-02-19 11:50
as last field in VSEOCLASS, see https://github.com/ivanfemia/abap2xlsx/pull/518/files

```
    <WITH_UNIT_TESTS>X</WITH_UNIT_TESTS>
   </VSEOCLASS>
```

**Comment by MLDOliveira** [comment] 2018-02-19 11:58
After change the file and try to install abap2xlsx again I have a new erro:

Error from IF_PACKAGE->SET_ALL_ATTRIBUTES 8

Could you help me again @larshp ?

**Comment by larshp** [comment] 2018-02-19 12:54
try setting a breakpoint here, https://github.com/larshp/abapGit/blob/master/src/objects/zcl_abapgit_object_devc.clas.abap#L304

looks like the transport layer is invalid
