### ISSUE TITLE
Error: Could not acquire lock USER [username]

### ISSUE THREAD

**Issue by nununo** [larshp/abapGit#474] opened 2016-11-29 10:46 UTC
Hello,

Suddenly I started getting this error every time I tried to set a repository as favorite or switch to another repository using the burger icon:

![image](https://cloud.githubusercontent.com/assets/532049/20706654/3dcdd48e-b620-11e6-8977-090d32c16942.png)

But then it stopped happening again and now everything is working fine...

Weird.

Cheers,
Nuno

**Comment by EduardoCopat** [comment] 2016-11-29 11:48
I also received this error a few days ago. I had a lock on the ZABAPGIT table. I went to SM12 and killed all sessions and then everything was working fine again.

**Comment by sbcgua** [comment] 2016-11-29 12:30
seems that something is still wrong with those commits

**Comment by EduardoCopat** [comment] 2016-11-29 12:39
May also happen when two ZABAPGITs are running concurrently

**Comment by EduardoCopat** [comment] 2017-01-22 14:35
@nununo Have you received this error again? I couldn't reproduce it again using two abapgits session concurrently. Should we close this issue?

**Comment by larshp** [comment] 2017-01-22 14:36
I think lets close it, open a new if the error occurs again, and provide steps to reproduce

**Closed by larshp** 2017-01-22 14:36 UTC
Labels: bug

**Comment by nununo** [comment] 2017-01-22 16:29
Never again ;)
