### ISSUE TITLE
Error: error from RS_CUA_INTERNAL_FETCH 

### ISSUE THREAD

**Issue by chund** [larshp/abapGit#1899] opened 2018-09-07 14:17 UTC
Since some updates (most probably SAP-note 2685155) were applied to our ABAP 750 System we get following error at several actions in ABAPGit:
Error: error from RS_CUA_INTERNAL_FETCH 

It always occurs when a function group has no CUA.

I wonder if the raise in METHOD serialize_cua could simply be removed ...?

At least it fixed the issue for me.

**Comment by larshp** [comment] 2018-09-07 15:07
Hi,
Can you help checking the value of `sy-subrc`? Looks like the note adds `RAISE not_found`, so the IF after the call to function module RS_CUA_INTERNAL_FETCH might have to be changed to `IF sy-subrc > 1.` instead of `IF sy-subrc <> 0.`

**Comment by larshp** [comment] 2018-09-07 15:14
Issue reproduced after implementing note 2685155,
![image](https://user-images.githubusercontent.com/5888506/45227720-7075ca00-b2c1-11e8-96fc-5d8fb859bb88.png)

**Comment by larshp** [comment] 2018-09-08 07:00
@chund try again, latest version

**Comment by larshp** [comment] 2018-09-12 09:08
closing

**Closed by larshp** 2018-09-12 09:08 UTC
Labels: bug
